name: lighthouse
version: 0.4.1+6
publish_to: none
description: An illuminated physical play surface for Looney Pyramids.

environment:
  sdk: '>=3.13.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^12.3.0
  file_saver: ^0.4.0
  device_info_plus: ^13.2.0
  screen_brightness: ^2.1.11
  sensors_plus: ^7.1.0
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  wakelock_plus: ^1.8.0
  cryptography: ^2.8.1
  flutter_webrtc: ^1.6.2+hotfix.3
  mqtt_client: ^10.11.11
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
