import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

enum AppLanguage {
  english,
  spanish,
  japanese,
  german,
  french,
  dutch,
  portuguese,
  chinese,
  italian,
  tokiPona,
}

extension AppLanguageInfo on AppLanguage {
  String get code => switch (this) {
    AppLanguage.english => 'en',
    AppLanguage.spanish => 'es',
    AppLanguage.japanese => 'ja',
    AppLanguage.german => 'de',
    AppLanguage.french => 'fr',
    AppLanguage.dutch => 'nl',
    AppLanguage.portuguese => 'pt',
    AppLanguage.chinese => 'zh',
    AppLanguage.italian => 'it',
    AppLanguage.tokiPona => 'tok',
  };

  String get selfName => switch (this) {
    AppLanguage.english => 'English',
    AppLanguage.spanish => 'Español',
    AppLanguage.japanese => '日本語',
    AppLanguage.german => 'Deutsch',
    AppLanguage.french => 'Français',
    AppLanguage.dutch => 'Nederlands',
    AppLanguage.portuguese => 'Português',
    AppLanguage.chinese => '中文',
    AppLanguage.italian => 'Italiano',
    AppLanguage.tokiPona => 'toki pona',
  };
}

class AppLanguageController {
  AppLanguageController._();

  static const _preferenceKey = 'lighthouse.language.v1';
  static final ValueNotifier<AppLanguage> notifier = ValueNotifier(
    AppLanguage.english,
  );

  static AppLanguage get current => notifier.value;

  static Future<void> load() async {
    final preferences = await SharedPreferences.getInstance();
    final code = preferences.getString(_preferenceKey);
    notifier.value = AppLanguage.values.firstWhere(
      (language) => language.code == code,
      orElse: () => AppLanguage.english,
    );
  }

  static Future<void> set(AppLanguage language) async {
    if (notifier.value == language) return;
    notifier.value = language;
    final preferences = await SharedPreferences.getInstance();
    await preferences.setString(_preferenceKey, language.code);
  }
}

String tr(String english) {
  final language = AppLanguageController.current;
  return switch (language) {
    AppLanguage.english => english,
    AppLanguage.spanish => _es[english] ?? _esExtra[english] ?? english,
    AppLanguage.japanese => _ja[english] ?? _jaExtra[english] ?? english,
    AppLanguage.german => _de[english] ?? english,
    AppLanguage.french => _fr[english] ?? english,
    AppLanguage.dutch => _nl[english] ?? english,
    AppLanguage.portuguese => _pt[english] ?? english,
    AppLanguage.chinese => _zh[english] ?? english,
    AppLanguage.italian => _it[english] ?? english,
    AppLanguage.tokiPona => _tok[english] ?? english,
  };
}

const _es = <String, String>{
  'Desktop / trackpad': 'Escritorio / panel táctil',
  'Android tablet': 'Tableta Android',
  'Android phone': 'Teléfono Android',
  'Touch device': 'Dispositivo táctil',
  'Light Lottery': 'Lotería de luz',
  'Entropy Delete': 'Borrado entrópico',
  'Turn Timer': 'Temporizador de turno',
  'Red Sweep': 'Barrido rojo',
  'Ghost Paths': 'Rastros fantasma',
  'Random Event Zone': 'Zona de evento aleatorio',
  'Breathing': 'Respiración',
  'Nest Cycle': 'Ciclo de nido',
  'Radar': 'Radar',
  'Dice Bubble': 'Burbuja de dados',
  'Side Guns': 'Cañones laterales',
  'Corner Ricochet': 'Rebote de esquina',
  'Hot Potato': 'Patata caliente',
  'Constellation Draw': 'Dibujar constelación',
  'Heartbeat': 'Latido',
  'Triangle Bounce': 'Rebote triangular',
  'Square Chase': 'Persecución cuadrada',
  'Press/release to roll; two-finger drag moves; latch tiles cycle die counts':
      'Pulsa y suelta para lanzar; arrastra con dos dedos para mover; las fichas del cierre cambian la cantidad de dados',
  'Tap or hold/release to roll; two-finger drag moves; pinch resizes; latch tiles cycle die counts':
      'Toca o mantén y suelta para lanzar; arrastra con dos dedos para mover; pellizca para cambiar el tamaño; las fichas del cierre cambian la cantidad de dados',
  'Tap or drag from tray; drag stones; double-click to remove':
      'Toca o arrastra desde la bandeja; arrastra las piedras; doble clic para quitar',
  'Tap or drag from tray; drag stones; double-tap to remove':
      'Toca o arrastra desde la bandeja; arrastra las piedras; doble toque para quitar',
  'Thanks for playing with LightHouse!': '¡Gracias por jugar con LightHouse!',
  'Menu': 'Menú', 'File': 'Archivo', 'Edit': 'Editar',
  'Boards': 'Tableros', 'Toys': 'Juguetes', 'Display': 'Pantalla',
  'Remote': 'Remoto', 'Instructions': 'Instrucciones',
  'New': 'Nuevo', 'Open…': 'Abrir…',
  'Restore Previous Autosave…': 'Restaurar autoguardado anterior…',
  'Save': 'Guardar', 'Save a Copy…': 'Guardar una copia…',
  'Rename…': 'Renombrar…',
  'Import Table JSON…': 'Importar JSON de mesa…',
  'Export Table JSON…': 'Exportar JSON de mesa…',
  'Undo': 'Deshacer', 'Redo': 'Rehacer',
  'Rotation Snap': 'Ajuste de rotación', 'Free Rotation': 'Rotación libre',
  'Snap Now': 'Ajustar ahora', 'Game Boards': 'Tableros de juego',
  'Grids': 'Cuadrículas', 'Martian Chess': 'Ajedrez marciano',
  'Snap pieces to board': 'Ajustar piezas al tablero', 'None': 'Ninguno',
  'Checker Shading': 'Sombreado ajedrezado', 'Size': 'Tamaño',
  'Safety Points': 'Puntas seguras', 'Brightness': 'Brillo',
  'Orientation Lock': 'Bloqueo de orientación',
  'Full-screen': 'Pantalla completa',
  'Zendo Off · Normal LightHouse': 'Zendo apagado · LightHouse normal',
  'Zendo Stones': 'Piedras Zendo', 'Classic': 'Clásico',
  'Classic + Zendo 2.0': 'Clásico + Zendo 2.0',
  'Zendo Rule': 'Regla Zendo',
  'Different Zendo Rule': 'Otra regla Zendo',
  'Complex Rules': 'Reglas complejas',
  'Hide Active Rule': 'Ocultar regla activa',
  'Show Active Rule': 'Mostrar regla activa',
  'Easy': 'Fácil', 'Medium': 'Media', 'Hard': 'Difícil',
  'This Device: Table Display': 'Este dispositivo: Pantalla de mesa',
  'This Device: Controller': 'Este dispositivo: Controlador',
  'Pair with 6-Character Code': 'Emparejar con código de 6 caracteres',
  'Pair with QR / Link': 'Emparejar con QR / enlace',
  'Add Another Controller': 'Añadir otro controlador',
  'Show Pairing QR': 'Mostrar QR de emparejamiento',
  'Swap Roles': 'Intercambiar funciones', 'Disconnect': 'Desconectar',
  'Turn Off All Ripples': 'Apagar todas las ondas',
  'Table Display Shape Interaction': 'Interacción con formas en la pantalla de mesa',
  'Table Display Shapes Visible': 'Formas visibles en la pantalla de mesa',
  'Create / resize / delete': 'Crear / redimensionar / eliminar',
  'Double-click': 'Doble clic', 'Double-tap': 'Doble toque',
  'Tip / stand': 'Tumbar / levantar',
  'Drag through the footprint edge': 'Arrastra atravesando el borde de la huella',
  'Full / wall light': 'Luz completa / pared',
  'Draw a loop around an upright footprint': 'Dibuja un bucle alrededor de una huella vertical',
  'Move': 'Mover',
  'Two-finger scroll over a footprint': 'Desplaza con dos dedos sobre una huella',
  'Rotate': 'Rotar', 'Shift + two-finger scroll': 'Mayús + desplazamiento con dos dedos',
  'Move + rotate': 'Mover + rotar',
  'Two-finger drag and twist': 'Arrastra y gira con dos dedos',
  'Rotation snap': 'Ajuste de rotación',
  'Edit > Rotation Snap; Snap Now aligns every shape immediately':
      'Editar > Ajuste de rotación; Ajustar ahora alinea todas las formas inmediatamente',
  'Board snap': 'Ajuste al tablero',
  'Boards > Snap pieces to board': 'Tableros > Ajustar piezas al tablero',
  'Dice bubble': 'Burbuja de dados',
  'Zendo stones': 'Piedras Zendo',
  'Remote ripple': 'Onda remota',
  'On a Controller, hold a shape to start its ripple; hold again to stop it':
      'En un Controlador, mantén una forma para iniciar su onda; mantén de nuevo para detenerla',
  'Toys chooses controls; hold an icon for its name':
      'Juguetes elige controles; mantén un icono para ver su nombre',
  'Close instructions': 'Cerrar instrucciones',
  'Calibrate physical size': 'Calibrar tamaño físico',
  'Ruler': 'Regla', 'Large pyramid': 'Pirámide grande',
  'Cancel': 'Cancelar', 'Use calibration': 'Usar calibración',
  'A Large upright pyramid should fit this square:':
      'Una pirámide grande vertical debe encajar en este cuadrado:',
  'Cross-check: this bar should measure exactly 25 mm:':
      'Comprobación: esta barra debe medir exactamente 25 mm:',
  'Recalibrate': 'Recalibrar', 'Looks right': 'Se ve bien',
  'Dice': 'Dados', 'selected': 'seleccionados',
  'Regular D6': 'D6 normal', 'Lightning die': 'Dado relámpago',
  'Pyramid die': 'Dado pirámide', 'Treehouse die': 'Dado Treehouse',
  'Color die': 'Dado de color', 'Fudge / Fate die': 'Dado Fudge / Fate',
  'Remove one': 'Quitar uno', 'Add one': 'Añadir uno', 'Done': 'Listo',
};

const _ja = <String, String>{
  'Desktop / trackpad': 'デスクトップ / トラックパッド',
  'Android tablet': 'Androidタブレット',
  'Android phone': 'Androidスマートフォン',
  'Touch device': 'タッチ端末',
  'Light Lottery': 'ライト・ロッタリー',
  'Entropy Delete': 'エントロピー削除',
  'Turn Timer': 'ターンタイマー',
  'Red Sweep': 'レッドスイープ',
  'Ghost Paths': 'ゴーストパス',
  'Random Event Zone': 'ランダムイベントゾーン',
  'Breathing': 'ブリージング',
  'Nest Cycle': 'ネストサイクル',
  'Radar': 'レーダー',
  'Dice Bubble': 'ダイスバブル',
  'Side Guns': 'サイドガン',
  'Corner Ricochet': 'コーナー跳弾',
  'Hot Potato': 'ホットポテト',
  'Constellation Draw': '星座描画',
  'Heartbeat': 'ハートビート',
  'Triangle Bounce': 'トライアングルバウンス',
  'Square Chase': 'スクエアチェイス',
  'Press/release to roll; two-finger drag moves; latch tiles cycle die counts':
      '押して離すとロール。2本指ドラッグで移動。ラッチでダイス数を変更',
  'Tap or hold/release to roll; two-finger drag moves; pinch resizes; latch tiles cycle die counts':
      'タップまたは長押しして離すとロール。2本指ドラッグで移動。ピンチでサイズ変更。ラッチでダイス数を変更',
  'Tap or drag from tray; drag stones; double-click to remove':
      'トレイからタップまたはドラッグ。ストーンをドラッグ。ダブルクリックで削除',
  'Tap or drag from tray; drag stones; double-tap to remove':
      'トレイからタップまたはドラッグ。ストーンをドラッグ。ダブルタップで削除',
  'Thanks for playing with LightHouse!': 'LightHouseで遊んでくれてありがとう！',
  'Menu': 'メニュー', 'File': 'ファイル', 'Edit': '編集',
  'Boards': 'ボード', 'Toys': 'トイ', 'Display': '表示',
  'Remote': 'リモート', 'Instructions': '説明',
  'New': '新規', 'Open…': '開く…',
  'Restore Previous Autosave…': '前の自動保存を復元…',
  'Save': '保存', 'Save a Copy…': 'コピーを保存…',
  'Rename…': '名前を変更…',
  'Import Table JSON…': 'テーブルJSONを読み込む…',
  'Export Table JSON…': 'テーブルJSONを書き出す…',
  'Undo': '元に戻す', 'Redo': 'やり直す',
  'Rotation Snap': '回転スナップ', 'Free Rotation': '自由回転',
  'Snap Now': '今すぐスナップ', 'Game Boards': 'ゲームボード',
  'Grids': 'グリッド', 'Martian Chess': 'マーシャン・チェス',
  'Snap pieces to board': '駒をボードにスナップ', 'None': 'なし',
  'Checker Shading': '市松模様', 'Size': 'サイズ',
  'Safety Points': '安全な先端', 'Brightness': '明るさ',
  'Orientation Lock': '向きのロック', 'Full-screen': '全画面',
  'Zendo Off · Normal LightHouse': 'Zendoオフ · 通常のLightHouse',
  'Zendo Stones': 'Zendoストーン', 'Classic': 'クラシック',
  'Classic + Zendo 2.0': 'クラシック + Zendo 2.0',
  'Zendo Rule': 'Zendoルール', 'Different Zendo Rule': '別のZendoルール',
  'Complex Rules': '複雑なルール',
  'Hide Active Rule': '現在のルールを隠す',
  'Show Active Rule': '現在のルールを表示',
  'Easy': 'かんたん', 'Medium': 'ふつう', 'Hard': 'むずかしい',
  'This Device: Table Display': 'この端末：テーブル表示',
  'This Device: Controller': 'この端末：コントローラー',
  'Pair with 6-Character Code': '6文字コードでペアリング',
  'Pair with QR / Link': 'QR / リンクでペアリング',
  'Add Another Controller': 'コントローラーを追加',
  'Show Pairing QR': 'ペアリングQRを表示',
  'Swap Roles': '役割を交換', 'Disconnect': '切断',
  'Turn Off All Ripples': 'すべての波紋をオフ',
  'Table Display Shape Interaction': 'テーブル表示で形を操作',
  'Table Display Shapes Visible': 'テーブル表示で形を表示',
  'Create / resize / delete': '作成 / サイズ変更 / 削除',
  'Double-click': 'ダブルクリック', 'Double-tap': 'ダブルタップ',
  'Tip / stand': '倒す / 立てる',
  'Drag through the footprint edge': 'フットプリントの端を越えてドラッグ',
  'Full / wall light': '全面 / 壁面ライト',
  'Draw a loop around an upright footprint': '立っているフットプリントを囲むようにループを描く',
  'Move': '移動', 'Two-finger scroll over a footprint': 'フットプリント上で2本指スクロール',
  'Rotate': '回転', 'Shift + two-finger scroll': 'Shift + 2本指スクロール',
  'Move + rotate': '移動 + 回転',
  'Two-finger drag and twist': '2本指でドラッグしてひねる',
  'Rotation snap': '回転スナップ',
  'Edit > Rotation Snap; Snap Now aligns every shape immediately':
      '編集 > 回転スナップ。「今すぐスナップ」ですべての形をすぐに揃えます',
  'Board snap': 'ボードスナップ',
  'Boards > Snap pieces to board': 'ボード > 駒をボードにスナップ',
  'Dice bubble': 'ダイスバブル', 'Zendo stones': 'Zendoストーン',
  'Remote ripple': 'リモート波紋',
  'On a Controller, hold a shape to start its ripple; hold again to stop it':
      'コントローラーで形を長押しすると波紋が始まり、もう一度長押しすると止まります',
  'Toys chooses controls; hold an icon for its name':
      'トイでコントロールを選択。アイコンを長押しすると名前を表示',
  'Close instructions': '説明を閉じる',
  'Calibrate physical size': '実寸を調整',
  'Ruler': '定規', 'Large pyramid': 'ラージ・ピラミッド',
  'Cancel': 'キャンセル', 'Use calibration': 'この調整を使う',
  'A Large upright pyramid should fit this square:':
      '立てたラージ・ピラミッドがこの四角にぴったり収まるはずです：',
  'Cross-check: this bar should measure exactly 25 mm:':
      '確認：このバーはちょうど25 mmです：',
  'Recalibrate': '再調整', 'Looks right': 'これでOK',
  'Dice': 'ダイス', 'selected': '選択',
  'Regular D6': '通常D6', 'Lightning die': 'ライトニング・ダイス',
  'Pyramid die': 'ピラミッド・ダイス',
  'Treehouse die': 'ツリーハウス・ダイス',
  'Color die': 'カラー・ダイス', 'Fudge / Fate die': 'Fudge / Fateダイス',
  'Remove one': '1個減らす', 'Add one': '1個増やす', 'Done': '完了',
};


const _esExtra = <String, String>{

  'Difficulty': 'Dificultad',
  'Medium Hard': 'Media difícil',
  'Crazy Hard': 'Extremadamente difícil',
  'increments': 'incrementos',
  'Manual calibration': 'Calibración manual',
  'Pairing code': 'Código de emparejamiento',
  'Type the same 6-character code on both devices.': 'Escribe el mismo código de 6 caracteres en ambos dispositivos.',
  'Enter exactly 6 letters or digits.': 'Introduce exactamente 6 letras o dígitos.',
  'Add Controller': 'Añadir controlador',
  'Pair Controller': 'Emparejar controlador',
  'Pair Table Display': 'Emparejar pantalla de mesa',
  'Enter this same code on the other device and choose the opposite role.': 'Introduce este mismo código en el otro dispositivo y elige el rol opuesto.',
  'Paired': 'Emparejado',
  'Pairing service unavailable.': 'Servicio de emparejamiento no disponible.',
  'Waiting for the other device': 'Esperando al otro dispositivo',
  'LightHouse locks the table to one orientation while it is open. Android can open the system Display settings directly.': 'LightHouse fija la mesa en una orientación mientras está abierta. Android puede abrir directamente los ajustes de pantalla del sistema.',
  'LightHouse locks the table while it is open. iOS does not provide a supported app link to Rotation Lock; change it in Control Center.': 'LightHouse fija la mesa mientras está abierta. iOS no ofrece un enlace compatible al bloqueo de rotación; cámbialo en el Centro de control.',
  'Orientation locking depends on browser and platform support.': 'El bloqueo de orientación depende del navegador y de la plataforma.',

  'Motion access was not granted.': 'No se concedió acceso al movimiento.',
  'Pairing code copied.': 'Código de emparejamiento copiado.',
  'Pairing link copied.': 'Enlace de emparejamiento copiado.',
  'Copy Code': 'Copiar código',
  'Copy Link': 'Copiar enlace',
  'Hide': 'Ocultar',
  'Pair by Code': 'Emparejar por código',
  'Pair': 'Emparejar',
  'Controller': 'Controlador',
  'Table Display': 'Pantalla de mesa',
  'Disconnect Table Display': 'Desconectar pantalla de mesa',
  'Table Display shape interaction': 'Interacción con formas en la pantalla de mesa',
  'Table Display shapes visible': 'Formas visibles en la pantalla de mesa',
  'Turn off all ripples': 'Apagar todas las ondas',
  'Table name': 'Nombre de la mesa',
  'OK': 'Aceptar',
  'Restore previous autosave?': '¿Restaurar el autoguardado anterior?',
  'Restore': 'Restaurar',
  'Previous autosave restored. Undo can reverse it.': 'Autoguardado anterior restaurado. Deshacer puede revertirlo.',
  'Saved a copy.': 'Copia guardada.',
  'Table saved.': 'Mesa guardada.',
  'No saved tables yet.': 'Aún no hay mesas guardadas.',
  'Delete saved table': 'Eliminar mesa guardada',
  'Table JSON saved.': 'JSON de mesa guardado.',
  'That file is not a LightHouse table.': 'Ese archivo no es una mesa de LightHouse.',
  'Could not read that table file.': 'No se pudo leer ese archivo de mesa.',
  'Could not open Android display settings.': 'No se pudieron abrir los ajustes de pantalla de Android.',
  'Orientation lock': 'Bloqueo de orientación',
  'Display settings': 'Ajustes de pantalla',
  'Browsers cannot control screen brightness. Use the device brightness control.': 'Los navegadores no pueden controlar el brillo de la pantalla. Usa el control de brillo del dispositivo.',
  'Table brightness': 'Brillo de la mesa',
  'iOS does not expose a supported deep link to its Brightness panel; use Control Center for the system setting.': 'iOS no ofrece un enlace compatible al panel de brillo; usa el Centro de control.',
  'Use system': 'Usar sistema',
  'On iPhone or iPad, open this site in Safari, tap Share, then Add to Home Screen. On desktop browsers, use the browser install-app command when offered.': 'En iPhone o iPad, abre este sitio en Safari, toca Compartir y luego Añadir a pantalla de inicio. En navegadores de escritorio, usa la opción de instalar la aplicación cuando aparezca.',
  'Different rule': 'Otra regla',
  'Hide rule': 'Ocultar regla',
  'Place a Large pyramid upright over the filled square. Adjust the slider until its base matches the square exactly.': 'Coloca una pirámide grande de pie sobre el cuadrado relleno. Ajusta el control hasta que la base coincida exactamente.',
  'Hold a ruler to the screen with 0 aligned to the fixed left end. Adjust the slider until the right end reaches exactly 50 mm.': 'Sostén una regla sobre la pantalla con el 0 alineado al extremo izquierdo fijo. Ajusta el control hasta que el extremo derecho llegue exactamente a 50 mm.',
};

const _jaExtra = <String, String>{

  'Difficulty': '難易度',
  'Medium Hard': 'やや難しい',
  'Crazy Hard': '非常に難しい',
  'increments': '刻み',
  'Manual calibration': '手動調整',
  'Pairing code': 'ペアリングコード',
  'Type the same 6-character code on both devices.': '両方の端末に同じ6文字コードを入力してください。',
  'Enter exactly 6 letters or digits.': '英数字をちょうど6文字入力してください。',
  'Add Controller': 'コントローラーを追加',
  'Pair Controller': 'コントローラーをペアリング',
  'Pair Table Display': 'テーブル表示をペアリング',
  'Enter this same code on the other device and choose the opposite role.': 'もう一方の端末にも同じコードを入力し、反対の役割を選んでください。',
  'Paired': 'ペアリング済み',
  'Pairing service unavailable.': 'ペアリングサービスを利用できません。',
  'Waiting for the other device': 'もう一方の端末を待っています',
  'LightHouse locks the table to one orientation while it is open. Android can open the system Display settings directly.': 'LightHouseを開いている間、テーブルの向きを固定します。Androidではシステムの画面設定を直接開けます。',
  'LightHouse locks the table while it is open. iOS does not provide a supported app link to Rotation Lock; change it in Control Center.': 'LightHouseを開いている間、テーブルの向きを固定します。iOSでは回転ロックへの対応リンクがないため、コントロールセンターで変更してください。',
  'Orientation locking depends on browser and platform support.': '向きの固定はブラウザとプラットフォームの対応状況によります。',

  'Motion access was not granted.': 'モーションへのアクセスが許可されませんでした。',
  'Pairing code copied.': 'ペアリングコードをコピーしました。',
  'Pairing link copied.': 'ペアリングリンクをコピーしました。',
  'Copy Code': 'コードをコピー',
  'Copy Link': 'リンクをコピー',
  'Hide': '隠す',
  'Pair by Code': 'コードでペアリング',
  'Pair': 'ペアリング',
  'Controller': 'コントローラー',
  'Table Display': 'テーブル表示',
  'Disconnect Table Display': 'テーブル表示を切断',
  'Table Display shape interaction': 'テーブル表示で形を操作',
  'Table Display shapes visible': 'テーブル表示で形を表示',
  'Turn off all ripples': 'すべての波紋をオフ',
  'Table name': 'テーブル名',
  'OK': 'OK',
  'Restore previous autosave?': '前の自動保存を復元しますか？',
  'Restore': '復元',
  'Previous autosave restored. Undo can reverse it.': '前の自動保存を復元しました。「元に戻す」で取り消せます。',
  'Saved a copy.': 'コピーを保存しました。',
  'Table saved.': 'テーブルを保存しました。',
  'No saved tables yet.': '保存されたテーブルはまだありません。',
  'Delete saved table': '保存したテーブルを削除',
  'Table JSON saved.': 'テーブルJSONを保存しました。',
  'That file is not a LightHouse table.': 'そのファイルはLightHouseのテーブルではありません。',
  'Could not read that table file.': 'テーブルファイルを読み込めませんでした。',
  'Could not open Android display settings.': 'Androidの画面設定を開けませんでした。',
  'Orientation lock': '向きのロック',
  'Display settings': '画面設定',
  'Browsers cannot control screen brightness. Use the device brightness control.': 'ブラウザから画面の明るさは変更できません。端末の明るさ設定を使ってください。',
  'Table brightness': 'テーブルの明るさ',
  'iOS does not expose a supported deep link to its Brightness panel; use Control Center for the system setting.': 'iOSでは明るさ設定への対応リンクがありません。コントロールセンターを使ってください。',
  'Use system': 'システム設定を使う',
  'On iPhone or iPad, open this site in Safari, tap Share, then Add to Home Screen. On desktop browsers, use the browser install-app command when offered.': 'iPhoneまたはiPadではSafariでこのサイトを開き、共有から「ホーム画面に追加」を選びます。デスクトップでは、表示された場合にブラウザのアプリをインストールする機能を使います。',
  'Different rule': '別のルール',
  'Hide rule': 'ルールを隠す',
  'Place a Large pyramid upright over the filled square. Adjust the slider until its base matches the square exactly.': 'ラージ・ピラミッドを立てて塗りつぶした四角に重ね、底面が正確に一致するまでスライダーを調整します。',
  'Hold a ruler to the screen with 0 aligned to the fixed left end. Adjust the slider until the right end reaches exactly 50 mm.': '定規の0を固定された左端に合わせ、右端がちょうど50 mmになるまでスライダーを調整します。',
};

const _de = <String, String>{
  'Desktop / trackpad': 'Desktop / Trackpad',
  'Android tablet': 'Android-Tablet',
  'Android phone': 'Android-Telefon',
  'Touch device': 'Touch-Gerät',
  'Light Lottery': 'Lichtlotterie',
  'Entropy Delete': 'Entropie-Löschen',
  'Turn Timer': 'Zugtimer',
  'Red Sweep': 'Roter Sweep',
  'Ghost Paths': 'Geisterpfade',
  'Random Event Zone': 'Zufallsereignis-Zone',
  'Breathing': 'Atmung',
  'Nest Cycle': 'Nest-Zyklus',
  'Radar': 'Radar',
  'Dice Bubble': 'Würfelblase',
  'Side Guns': 'Seitenkanonen',
  'Corner Ricochet': 'Ecken-Ricochet',
  'Hot Potato': 'Heiße Kartoffel',
  'Constellation Draw': 'Sternbild zeichnen',
  'Heartbeat': 'Herzschlag',
  'Triangle Bounce': 'Dreieck-Sprung',
  'Square Chase': 'Quadrat-Jagd',
  'Thanks for playing with LightHouse!': 'Danke fürs Spielen mit LightHouse!',
  'Menu': 'Menü',
  'File': 'Datei',
  'Edit': 'Bearbeiten',
  'Boards': 'Bretter',
  'Toys': 'Spielzeuge',
  'Display': 'Anzeige',
  'Remote': 'Fernsteuerung',
  'Instructions': 'Anleitung',
  'New': 'Neu',
  'Open…': 'Öffnen…',
  'Restore Previous Autosave…': 'Vorherige Autospeicherung wiederherstellen…',
  'Save': 'Speichern',
  'Save a Copy…': 'Kopie speichern…',
  'Rename…': 'Umbenennen…',
  'Import Table JSON…': 'Tisch-JSON importieren…',
  'Export Table JSON…': 'Tisch-JSON exportieren…',
  'Undo': 'Rückgängig',
  'Redo': 'Wiederholen',
  'Rotation Snap': 'Rotationsraster',
  'Free Rotation': 'Freie Drehung',
  'Snap Now': 'Jetzt einrasten',
  'Game Boards': 'Spielbretter',
  'Grids': 'Raster',
  'Martian Chess': 'Martian Chess',
  'Snap pieces to board': 'Teile am Brett einrasten',
  'None': 'Keine',
  'Checker Shading': 'Schachbrett-Schattierung',
  'Size': 'Größe',
  'Safety Points': 'Sichere Spitzen',
  'Brightness': 'Helligkeit',
  'Orientation Lock': 'Ausrichtung sperren',
  'Full-screen': 'Vollbild',
  'Zendo Off · Normal LightHouse': 'Zendo aus · Normales LightHouse',
  'Zendo Stones': 'Zendo-Steine',
  'Classic': 'Klassisch',
  'Classic + Zendo 2.0': 'Klassisch + Zendo 2.0',
  'Zendo Rule': 'Zendo-Regel',
  'Different Zendo Rule': 'Andere Zendo-Regel',
  'Complex Rules': 'Komplexe Regeln',
  'Hide Active Rule': 'Aktive Regel ausblenden',
  'Show Active Rule': 'Aktive Regel anzeigen',
  'Easy': 'Leicht',
  'Medium': 'Mittel',
  'Medium Hard': 'Mittelschwer',
  'Hard': 'Schwer',
  'Crazy Hard': 'Extrem schwer',
  'Difficulty': 'Schwierigkeit',
  'This Device: Table Display': 'Dieses Gerät: Tischanzeige',
  'This Device: Controller': 'Dieses Gerät: Controller',
  'Pair with 6-Character Code': 'Mit 6-stelligem Code koppeln',
  'Pair with QR / Link': 'Mit QR / Link koppeln',
  'Add Another Controller': 'Weiteren Controller hinzufügen',
  'Show Pairing QR': 'Kopplungs-QR anzeigen',
  'Swap Roles': 'Rollen tauschen',
  'Disconnect': 'Trennen',
  'Turn Off All Ripples': 'Alle Wellen ausschalten',
  'Table Display Shape Interaction': 'Formen auf Tischanzeige bedienen',
  'Table Display Shapes Visible': 'Formen auf Tischanzeige sichtbar',
  'Create / resize / delete': 'Erstellen / Größe ändern / löschen',
  'Double-click': 'Doppelklick',
  'Double-tap': 'Doppeltippen',
  'Tip / stand': 'Kippen / aufstellen',
  'Drag through the footprint edge': 'Über den Rand der Grundfläche ziehen',
  'Full / wall light': 'Voll- / Wandlicht',
  'Draw a loop around an upright footprint': 'Eine Schleife um eine aufrechte Grundfläche zeichnen',
  'Move': 'Bewegen',
  'Two-finger scroll over a footprint': 'Mit zwei Fingern über einer Grundfläche scrollen',
  'Rotate': 'Drehen',
  'Shift + two-finger scroll': 'Umschalt + Zwei-Finger-Scroll',
  'Move + rotate': 'Bewegen + drehen',
  'Two-finger drag and twist': 'Mit zwei Fingern ziehen und drehen',
  'Rotation snap': 'Rotationsraster',
  'Edit > Rotation Snap; Snap Now aligns every shape immediately': 'Bearbeiten > Rotationsraster; Jetzt einrasten richtet alle Formen sofort aus',
  'Board snap': 'Brett-Raster',
  'Boards > Snap pieces to board': 'Bretter > Teile am Brett einrasten',
  'Dice bubble': 'Würfelblase',
  'Zendo stones': 'Zendo-Steine',
  'Remote ripple': 'Fern-Welle',
  'On a Controller, hold a shape to start its ripple; hold again to stop it': 'Auf einem Controller eine Form halten, um die Welle zu starten; erneut halten zum Stoppen',
  'Toys chooses controls; hold an icon for its name': 'Spielzeuge wählt Steuerungen; Symbol halten, um den Namen zu sehen',
  'Close instructions': 'Anleitung schließen',
  'Calibrate physical size': 'Physische Größe kalibrieren',
  'Ruler': 'Lineal',
  'Large pyramid': 'Große Pyramide',
  'Cancel': 'Abbrechen',
  'Use calibration': 'Kalibrierung verwenden',
  'A Large upright pyramid should fit this square:': 'Eine große aufrechte Pyramide sollte genau in dieses Quadrat passen:',
  'Cross-check: this bar should measure exactly 25 mm:': 'Gegenprüfung: Dieser Balken sollte genau 25 mm messen:',
  'Recalibrate': 'Neu kalibrieren',
  'Looks right': 'Sieht richtig aus',
  'Manual calibration': 'Manuelle Kalibrierung',
  'Dice': 'Würfel',
  'selected': 'ausgewählt',
  'Regular D6': 'Normaler W6',
  'Lightning die': 'Blitzwürfel',
  'Pyramid die': 'Pyramidenwürfel',
  'Treehouse die': 'Treehouse-Würfel',
  'Color die': 'Farbwürfel',
  'Fudge / Fate die': 'Fudge-/Fate-Würfel',
  'Remove one': 'Einen entfernen',
  'Add one': 'Einen hinzufügen',
  'Done': 'Fertig',
  'increments': 'Schritte',
  'Pairing code': 'Kopplungscode',
  'Type the same 6-character code on both devices.': 'Auf beiden Geräten denselben 6-stelligen Code eingeben.',
  'Enter exactly 6 letters or digits.': 'Genau 6 Buchstaben oder Ziffern eingeben.',
  'Add Controller': 'Controller hinzufügen',
  'Pair Controller': 'Controller koppeln',
  'Pair Table Display': 'Tischanzeige koppeln',
  'Enter this same code on the other device and choose the opposite role.': 'Diesen Code auf dem anderen Gerät eingeben und die entgegengesetzte Rolle wählen.',
  'Paired': 'Gekoppelt',
  'Pairing service unavailable.': 'Kopplungsdienst nicht verfügbar.',
  'Waiting for the other device': 'Warte auf das andere Gerät',
  'Motion access was not granted.': 'Bewegungszugriff wurde nicht gewährt.',
  'Pairing code copied.': 'Kopplungscode kopiert.',
  'Pairing link copied.': 'Kopplungslink kopiert.',
  'Copy Code': 'Code kopieren',
  'Copy Link': 'Link kopieren',
  'Hide': 'Ausblenden',
  'Pair by Code': 'Per Code koppeln',
  'Pair': 'Koppeln',
  'Controller': 'Controller',
  'Table Display': 'Tischanzeige',
  'Disconnect Table Display': 'Tischanzeige trennen',
  'Table Display shape interaction': 'Forminteraktion der Tischanzeige',
  'Table Display shapes visible': 'Formen der Tischanzeige sichtbar',
  'Turn off all ripples': 'Alle Wellen ausschalten',
  'Table name': 'Tischname',
  'OK': 'OK',
  'Restore previous autosave?': 'Vorherige Autospeicherung wiederherstellen?',
  'Restore': 'Wiederherstellen',
  'Previous autosave restored. Undo can reverse it.': 'Vorherige Autospeicherung wiederhergestellt. Rückgängig kann dies umkehren.',
  'Saved a copy.': 'Kopie gespeichert.',
  'Table saved.': 'Tisch gespeichert.',
  'No saved tables yet.': 'Noch keine gespeicherten Tische.',
  'Delete saved table': 'Gespeicherten Tisch löschen',
  'Table JSON saved.': 'Tisch-JSON gespeichert.',
  'That file is not a LightHouse table.': 'Diese Datei ist kein LightHouse-Tisch.',
  'Could not read that table file.': 'Tischdatei konnte nicht gelesen werden.',
  'Orientation lock': 'Ausrichtungssperre',
  'Display settings': 'Anzeigeeinstellungen',
  'Table brightness': 'Tischhelligkeit',
  'Use system': 'System verwenden',
  'Different rule': 'Andere Regel',
  'Hide rule': 'Regel ausblenden',
  'Press/release to roll; two-finger drag moves; latch tiles cycle die counts': 'Drücken/loslassen zum Würfeln; Zwei-Finger-Ziehen bewegt; Verriegelungsfelder ändern die Würfelanzahl',
  'Tap or hold/release to roll; two-finger drag moves; pinch resizes; latch tiles cycle die counts': 'Tippen oder halten/loslassen zum Würfeln; Zwei-Finger-Ziehen bewegt; Auf- und Zuziehen ändert die Größe; Verriegelungsfelder ändern die Würfelanzahl',
  'Tap or drag from tray; drag stones; double-click to remove': 'Aus der Ablage tippen oder ziehen; Steine ziehen; Doppelklick zum Entfernen',
  'Tap or drag from tray; drag stones; double-tap to remove': 'Aus der Ablage tippen oder ziehen; Steine ziehen; Doppeltippen zum Entfernen',
  'Place a Large pyramid upright over the filled square. Adjust the slider until its base matches the square exactly.': 'Eine große Pyramide aufrecht auf das ausgefüllte Quadrat stellen. Den Regler anpassen, bis die Grundfläche exakt passt.',
  'Hold a ruler to the screen with 0 aligned to the fixed left end. Adjust the slider until the right end reaches exactly 50 mm.': 'Ein Lineal mit 0 am festen linken Ende anlegen. Den Regler anpassen, bis das rechte Ende genau 50 mm erreicht.',
  'LightHouse locks the table to one orientation while it is open. Android can open the system Display settings directly.': 'LightHouse sperrt den Tisch während der Nutzung auf eine Ausrichtung. Android kann die System-Anzeigeeinstellungen direkt öffnen.',
  'LightHouse locks the table while it is open. iOS does not provide a supported app link to Rotation Lock; change it in Control Center.': 'LightHouse sperrt den Tisch während der Nutzung. iOS bietet keinen unterstützten App-Link zur Rotationssperre; ändere sie im Kontrollzentrum.',
  'Orientation locking depends on browser and platform support.': 'Die Ausrichtungssperre hängt von Browser- und Plattformunterstützung ab.',
  'Browsers cannot control screen brightness. Use the device brightness control.': 'Browser können die Bildschirmhelligkeit nicht steuern. Verwende die Helligkeitssteuerung des Geräts.',
  'iOS does not expose a supported deep link to its Brightness panel; use Control Center for the system setting.': 'iOS stellt keinen unterstützten Direktlink zum Helligkeitsbereich bereit; verwende das Kontrollzentrum.',
  'On iPhone or iPad, open this site in Safari, tap Share, then Add to Home Screen. On desktop browsers, use the browser install-app command when offered.': 'Auf iPhone oder iPad diese Seite in Safari öffnen, Teilen antippen und Zum Home-Bildschirm wählen. Auf Desktop-Browsern die angebotene App-Installation verwenden.',
  '6-Character Code': '6-stelliger Code',
  'QR / Link': 'QR / Link',
  'Could not open Android display settings.': 'Android-Anzeigeeinstellungen konnten nicht geöffnet werden.',
};

const _fr = <String, String>{
  'Desktop / trackpad': 'Ordinateur / pavé tactile',
  'Android tablet': 'Tablette Android',
  'Android phone': 'Téléphone Android',
  'Touch device': 'Appareil tactile',
  'Light Lottery': 'Loterie lumineuse',
  'Entropy Delete': 'Suppression entropique',
  'Turn Timer': 'Minuteur de tour',
  'Red Sweep': 'Balayage rouge',
  'Ghost Paths': 'Traînées fantômes',
  'Random Event Zone': 'Zone d’événement aléatoire',
  'Breathing': 'Respiration',
  'Nest Cycle': 'Cycle de nid',
  'Radar': 'Radar',
  'Dice Bubble': 'Bulle de dés',
  'Side Guns': 'Canons latéraux',
  'Corner Ricochet': 'Ricochet d’angle',
  'Hot Potato': 'Patate chaude',
  'Constellation Draw': 'Tracer une constellation',
  'Heartbeat': 'Battement de cœur',
  'Triangle Bounce': 'Rebond triangulaire',
  'Square Chase': 'Poursuite carrée',
  'Thanks for playing with LightHouse!': 'Merci de jouer avec LightHouse !',
  'Menu': 'Menu',
  'File': 'Fichier',
  'Edit': 'Modifier',
  'Boards': 'Plateaux',
  'Toys': 'Jouets',
  'Display': 'Affichage',
  'Remote': 'À distance',
  'Instructions': 'Instructions',
  'New': 'Nouveau',
  'Open…': 'Ouvrir…',
  'Restore Previous Autosave…': 'Restaurer l’enregistrement auto précédent…',
  'Save': 'Enregistrer',
  'Save a Copy…': 'Enregistrer une copie…',
  'Rename…': 'Renommer…',
  'Import Table JSON…': 'Importer le JSON de table…',
  'Export Table JSON…': 'Exporter le JSON de table…',
  'Undo': 'Annuler',
  'Redo': 'Rétablir',
  'Rotation Snap': 'Crantage de rotation',
  'Free Rotation': 'Rotation libre',
  'Snap Now': 'Aligner maintenant',
  'Game Boards': 'Plateaux de jeu',
  'Grids': 'Grilles',
  'Martian Chess': 'Échecs martiens',
  'Snap pieces to board': 'Aligner les pièces au plateau',
  'None': 'Aucun',
  'Checker Shading': 'Ombrage damier',
  'Size': 'Taille',
  'Safety Points': 'Pointes sûres',
  'Brightness': 'Luminosité',
  'Orientation Lock': 'Verrouillage de l’orientation',
  'Full-screen': 'Plein écran',
  'Zendo Off · Normal LightHouse': 'Zendo désactivé · LightHouse normal',
  'Zendo Stones': 'Pierres Zendo',
  'Classic': 'Classique',
  'Classic + Zendo 2.0': 'Classique + Zendo 2.0',
  'Zendo Rule': 'Règle Zendo',
  'Different Zendo Rule': 'Autre règle Zendo',
  'Complex Rules': 'Règles complexes',
  'Hide Active Rule': 'Masquer la règle active',
  'Show Active Rule': 'Afficher la règle active',
  'Easy': 'Facile',
  'Medium': 'Moyen',
  'Medium Hard': 'Assez difficile',
  'Hard': 'Difficile',
  'Crazy Hard': 'Très difficile',
  'Difficulty': 'Difficulté',
  'This Device: Table Display': 'Cet appareil : Affichage de table',
  'This Device: Controller': 'Cet appareil : Contrôleur',
  'Pair with 6-Character Code': 'Associer avec un code à 6 caractères',
  'Pair with QR / Link': 'Associer avec QR / lien',
  'Add Another Controller': 'Ajouter un autre contrôleur',
  'Show Pairing QR': 'Afficher le QR d’association',
  'Swap Roles': 'Échanger les rôles',
  'Disconnect': 'Déconnecter',
  'Turn Off All Ripples': 'Arrêter toutes les ondulations',
  'Table Display Shape Interaction': 'Interaction des formes sur l’affichage de table',
  'Table Display Shapes Visible': 'Formes visibles sur l’affichage de table',
  'Create / resize / delete': 'Créer / redimensionner / supprimer',
  'Double-click': 'Double-clic',
  'Double-tap': 'Double-toucher',
  'Tip / stand': 'Coucher / redresser',
  'Drag through the footprint edge': 'Faire glisser au-delà du bord de l’empreinte',
  'Full / wall light': 'Lumière pleine / murale',
  'Draw a loop around an upright footprint': 'Tracer une boucle autour d’une empreinte verticale',
  'Move': 'Déplacer',
  'Two-finger scroll over a footprint': 'Défiler à deux doigts sur une empreinte',
  'Rotate': 'Tourner',
  'Shift + two-finger scroll': 'Maj + défilement à deux doigts',
  'Move + rotate': 'Déplacer + tourner',
  'Two-finger drag and twist': 'Glisser et tourner à deux doigts',
  'Rotation snap': 'Crantage de rotation',
  'Edit > Rotation Snap; Snap Now aligns every shape immediately': 'Modifier > Crantage de rotation ; Aligner maintenant aligne immédiatement toutes les formes',
  'Board snap': 'Alignement au plateau',
  'Boards > Snap pieces to board': 'Plateaux > Aligner les pièces au plateau',
  'Dice bubble': 'Bulle de dés',
  'Zendo stones': 'Pierres Zendo',
  'Remote ripple': 'Ondulation distante',
  'On a Controller, hold a shape to start its ripple; hold again to stop it': 'Sur un contrôleur, maintenir une forme pour démarrer son ondulation ; maintenir à nouveau pour l’arrêter',
  'Toys chooses controls; hold an icon for its name': 'Jouets choisit les commandes ; maintenir une icône pour voir son nom',
  'Close instructions': 'Fermer les instructions',
  'Calibrate physical size': 'Calibrer la taille physique',
  'Ruler': 'Règle',
  'Large pyramid': 'Grande pyramide',
  'Cancel': 'Annuler',
  'Use calibration': 'Utiliser l’étalonnage',
  'A Large upright pyramid should fit this square:': 'Une grande pyramide verticale doit tenir exactement dans ce carré :',
  'Cross-check: this bar should measure exactly 25 mm:': 'Vérification : cette barre doit mesurer exactement 25 mm :',
  'Recalibrate': 'Recalibrer',
  'Looks right': 'Ça semble correct',
  'Manual calibration': 'Étalonnage manuel',
  'Dice': 'Dés',
  'selected': 'sélectionné',
  'Regular D6': 'D6 normal',
  'Lightning die': 'Dé éclair',
  'Pyramid die': 'Dé pyramide',
  'Treehouse die': 'Dé Treehouse',
  'Color die': 'Dé de couleur',
  'Fudge / Fate die': 'Dé Fudge / Fate',
  'Remove one': 'En retirer un',
  'Add one': 'En ajouter un',
  'Done': 'Terminé',
  'increments': 'crans',
  'Pairing code': 'Code d’association',
  'Type the same 6-character code on both devices.': 'Saisir le même code à 6 caractères sur les deux appareils.',
  'Enter exactly 6 letters or digits.': 'Saisir exactement 6 lettres ou chiffres.',
  'Add Controller': 'Ajouter un contrôleur',
  'Pair Controller': 'Associer le contrôleur',
  'Pair Table Display': 'Associer l’affichage de table',
  'Enter this same code on the other device and choose the opposite role.': 'Saisir ce même code sur l’autre appareil et choisir le rôle opposé.',
  'Paired': 'Associé',
  'Pairing service unavailable.': 'Service d’association indisponible.',
  'Waiting for the other device': 'En attente de l’autre appareil',
  'Motion access was not granted.': 'L’accès au mouvement n’a pas été accordé.',
  'Pairing code copied.': 'Code d’association copié.',
  'Pairing link copied.': 'Lien d’association copié.',
  'Copy Code': 'Copier le code',
  'Copy Link': 'Copier le lien',
  'Hide': 'Masquer',
  'Pair by Code': 'Associer par code',
  'Pair': 'Associer',
  'Controller': 'Contrôleur',
  'Table Display': 'Affichage de table',
  'Disconnect Table Display': 'Déconnecter l’affichage de table',
  'Table Display shape interaction': 'Interaction des formes de l’affichage de table',
  'Table Display shapes visible': 'Formes de l’affichage de table visibles',
  'Turn off all ripples': 'Arrêter toutes les ondulations',
  'Table name': 'Nom de la table',
  'OK': 'OK',
  'Restore previous autosave?': 'Restaurer l’enregistrement auto précédent ?',
  'Restore': 'Restaurer',
  'Previous autosave restored. Undo can reverse it.': 'Enregistrement auto précédent restauré. Annuler peut revenir en arrière.',
  'Saved a copy.': 'Copie enregistrée.',
  'Table saved.': 'Table enregistrée.',
  'No saved tables yet.': 'Aucune table enregistrée.',
  'Delete saved table': 'Supprimer la table enregistrée',
  'Table JSON saved.': 'JSON de table enregistré.',
  'That file is not a LightHouse table.': 'Ce fichier n’est pas une table LightHouse.',
  'Could not read that table file.': 'Impossible de lire ce fichier de table.',
  'Orientation lock': 'Verrouillage de l’orientation',
  'Display settings': 'Réglages d’affichage',
  'Table brightness': 'Luminosité de la table',
  'Use system': 'Utiliser le système',
  'Different rule': 'Autre règle',
  'Hide rule': 'Masquer la règle',
  'Press/release to roll; two-finger drag moves; latch tiles cycle die counts': 'Appuyer/relâcher pour lancer ; glisser à deux doigts pour déplacer ; les tuiles de verrou changent le nombre de dés',
  'Tap or hold/release to roll; two-finger drag moves; pinch resizes; latch tiles cycle die counts': 'Toucher ou maintenir/relâcher pour lancer ; glisser à deux doigts pour déplacer ; pincer pour redimensionner ; les tuiles de verrou changent le nombre de dés',
  'Tap or drag from tray; drag stones; double-click to remove': 'Toucher ou faire glisser depuis le bac ; faire glisser les pierres ; double-clic pour retirer',
  'Tap or drag from tray; drag stones; double-tap to remove': 'Toucher ou faire glisser depuis le bac ; faire glisser les pierres ; double-toucher pour retirer',
  'Place a Large pyramid upright over the filled square. Adjust the slider until its base matches the square exactly.': 'Placez une grande pyramide debout sur le carré rempli. Ajustez le curseur jusqu’à ce que sa base corresponde exactement au carré.',
  'Hold a ruler to the screen with 0 aligned to the fixed left end. Adjust the slider until the right end reaches exactly 50 mm.': 'Placez une règle sur l’écran avec le 0 aligné sur l’extrémité gauche fixe. Ajustez le curseur jusqu’à exactement 50 mm.',
  'LightHouse locks the table to one orientation while it is open. Android can open the system Display settings directly.': 'LightHouse verrouille la table dans une orientation tant qu’elle est ouverte. Android peut ouvrir directement les réglages d’affichage du système.',
  'LightHouse locks the table while it is open. iOS does not provide a supported app link to Rotation Lock; change it in Control Center.': 'LightHouse verrouille la table tant qu’elle est ouverte. iOS ne fournit pas de lien pris en charge vers le verrouillage de rotation ; modifiez-le dans le Centre de contrôle.',
  'Orientation locking depends on browser and platform support.': 'Le verrouillage de l’orientation dépend du navigateur et de la plateforme.',
  'Browsers cannot control screen brightness. Use the device brightness control.': 'Les navigateurs ne peuvent pas contrôler la luminosité de l’écran. Utilisez le réglage de luminosité de l’appareil.',
  'iOS does not expose a supported deep link to its Brightness panel; use Control Center for the system setting.': 'iOS ne fournit pas de lien direct pris en charge vers le panneau Luminosité ; utilisez le Centre de contrôle.',
  'On iPhone or iPad, open this site in Safari, tap Share, then Add to Home Screen. On desktop browsers, use the browser install-app command when offered.': 'Sur iPhone ou iPad, ouvrez ce site dans Safari, touchez Partager puis Sur l’écran d’accueil. Sur ordinateur, utilisez la commande d’installation de l’application lorsqu’elle est proposée.',
  '6-Character Code': 'Code à 6 caractères',
  'QR / Link': 'QR / lien',
  'Could not open Android display settings.': 'Impossible d’ouvrir les réglages d’affichage Android.',
};

const _nl = <String, String>{
  'Desktop / trackpad': 'Desktop / trackpad',
  'Android tablet': 'Android-tablet',
  'Android phone': 'Android-telefoon',
  'Touch device': 'Aanraakapparaat',
  'Light Lottery': 'Lichtloterij',
  'Entropy Delete': 'Entropie wissen',
  'Turn Timer': 'Beurttimer',
  'Red Sweep': 'Rode sweep',
  'Ghost Paths': 'Spookpaden',
  'Random Event Zone': 'Willekeurige gebeurteniszone',
  'Breathing': 'Ademhaling',
  'Nest Cycle': 'Nestcyclus',
  'Radar': 'Radar',
  'Dice Bubble': 'Dobbelsteenbel',
  'Side Guns': 'Zijkanonnen',
  'Corner Ricochet': 'Hoekricochet',
  'Hot Potato': 'Hete aardappel',
  'Constellation Draw': 'Sterrenbeeld tekenen',
  'Heartbeat': 'Hartslag',
  'Triangle Bounce': 'Driehoekstuiter',
  'Square Chase': 'Vierkantjacht',
  'Thanks for playing with LightHouse!': 'Bedankt voor het spelen met LightHouse!',
  'Menu': 'Menu',
  'File': 'Bestand',
  'Edit': 'Bewerken',
  'Boards': 'Borden',
  'Toys': 'Speelgoed',
  'Display': 'Weergave',
  'Remote': 'Op afstand',
  'Instructions': 'Instructies',
  'New': 'Nieuw',
  'Open…': 'Openen…',
  'Restore Previous Autosave…': 'Vorige automatische opslag herstellen…',
  'Save': 'Opslaan',
  'Save a Copy…': 'Kopie opslaan…',
  'Rename…': 'Hernoemen…',
  'Import Table JSON…': 'Tafel-JSON importeren…',
  'Export Table JSON…': 'Tafel-JSON exporteren…',
  'Undo': 'Ongedaan maken',
  'Redo': 'Opnieuw',
  'Rotation Snap': 'Rotatiesnap',
  'Free Rotation': 'Vrije rotatie',
  'Snap Now': 'Nu uitlijnen',
  'Game Boards': 'Spelborden',
  'Grids': 'Rasters',
  'Martian Chess': 'Martian Chess',
  'Snap pieces to board': 'Stukken aan bord uitlijnen',
  'None': 'Geen',
  'Checker Shading': 'Dambordschaduw',
  'Size': 'Grootte',
  'Safety Points': 'Veilige punten',
  'Brightness': 'Helderheid',
  'Orientation Lock': 'Oriëntatievergrendeling',
  'Full-screen': 'Volledig scherm',
  'Zendo Off · Normal LightHouse': 'Zendo uit · Normaal LightHouse',
  'Zendo Stones': 'Zendo-stenen',
  'Classic': 'Klassiek',
  'Classic + Zendo 2.0': 'Klassiek + Zendo 2.0',
  'Zendo Rule': 'Zendo-regel',
  'Different Zendo Rule': 'Andere Zendo-regel',
  'Complex Rules': 'Complexe regels',
  'Hide Active Rule': 'Actieve regel verbergen',
  'Show Active Rule': 'Actieve regel tonen',
  'Easy': 'Makkelijk',
  'Medium': 'Gemiddeld',
  'Medium Hard': 'Tamelijk moeilijk',
  'Hard': 'Moeilijk',
  'Crazy Hard': 'Zeer moeilijk',
  'Difficulty': 'Moeilijkheid',
  'This Device: Table Display': 'Dit apparaat: Tafelweergave',
  'This Device: Controller': 'Dit apparaat: Controller',
  'Pair with 6-Character Code': 'Koppelen met 6-tekencode',
  'Pair with QR / Link': 'Koppelen met QR / link',
  'Add Another Controller': 'Nog een controller toevoegen',
  'Show Pairing QR': 'Koppel-QR tonen',
  'Swap Roles': 'Rollen wisselen',
  'Disconnect': 'Verbinding verbreken',
  'Turn Off All Ripples': 'Alle rimpels uitschakelen',
  'Table Display Shape Interaction': 'Vorminteractie op tafelweergave',
  'Table Display Shapes Visible': 'Vormen zichtbaar op tafelweergave',
  'Create / resize / delete': 'Maken / formaat wijzigen / verwijderen',
  'Double-click': 'Dubbelklikken',
  'Double-tap': 'Dubbeltikken',
  'Tip / stand': 'Kantelen / rechtop zetten',
  'Drag through the footprint edge': 'Door de rand van de voetafdruk slepen',
  'Full / wall light': 'Vol / wandlicht',
  'Draw a loop around an upright footprint': 'Teken een lus rond een rechtopstaande voetafdruk',
  'Move': 'Verplaatsen',
  'Two-finger scroll over a footprint': 'Met twee vingers scrollen over een voetafdruk',
  'Rotate': 'Draaien',
  'Shift + two-finger scroll': 'Shift + scrollen met twee vingers',
  'Move + rotate': 'Verplaatsen + draaien',
  'Two-finger drag and twist': 'Met twee vingers slepen en draaien',
  'Rotation snap': 'Rotatiesnap',
  'Edit > Rotation Snap; Snap Now aligns every shape immediately': 'Bewerken > Rotatiesnap; Nu uitlijnen lijnt alle vormen direct uit',
  'Board snap': 'Bordsnap',
  'Boards > Snap pieces to board': 'Borden > Stukken aan bord uitlijnen',
  'Dice bubble': 'Dobbelsteenbel',
  'Zendo stones': 'Zendo-stenen',
  'Remote ripple': 'Rimpel op afstand',
  'On a Controller, hold a shape to start its ripple; hold again to stop it': 'Houd op een controller een vorm vast om de rimpel te starten; houd opnieuw vast om te stoppen',
  'Toys chooses controls; hold an icon for its name': 'Speelgoed kiest bediening; houd een pictogram vast voor de naam',
  'Close instructions': 'Instructies sluiten',
  'Calibrate physical size': 'Fysieke grootte kalibreren',
  'Ruler': 'Liniaal',
  'Large pyramid': 'Grote piramide',
  'Cancel': 'Annuleren',
  'Use calibration': 'Kalibratie gebruiken',
  'A Large upright pyramid should fit this square:': 'Een grote rechtopstaande piramide moet precies in dit vierkant passen:',
  'Cross-check: this bar should measure exactly 25 mm:': 'Controle: deze balk moet exact 25 mm meten:',
  'Recalibrate': 'Opnieuw kalibreren',
  'Looks right': 'Ziet er goed uit',
  'Manual calibration': 'Handmatige kalibratie',
  'Dice': 'Dobbelstenen',
  'selected': 'geselecteerd',
  'Regular D6': 'Gewone D6',
  'Lightning die': 'Bliksemdobbelsteen',
  'Pyramid die': 'Piramidedobbelsteen',
  'Treehouse die': 'Treehouse-dobbelsteen',
  'Color die': 'Kleurdobbelsteen',
  'Fudge / Fate die': 'Fudge / Fate-dobbelsteen',
  'Remove one': 'Eén verwijderen',
  'Add one': 'Eén toevoegen',
  'Done': 'Klaar',
  'increments': 'stappen',
  'Pairing code': 'Koppelcode',
  'Type the same 6-character code on both devices.': 'Voer op beide apparaten dezelfde code van 6 tekens in.',
  'Enter exactly 6 letters or digits.': 'Voer precies 6 letters of cijfers in.',
  'Add Controller': 'Controller toevoegen',
  'Pair Controller': 'Controller koppelen',
  'Pair Table Display': 'Tafelweergave koppelen',
  'Enter this same code on the other device and choose the opposite role.': 'Voer deze code op het andere apparaat in en kies de tegenovergestelde rol.',
  'Paired': 'Gekoppeld',
  'Pairing service unavailable.': 'Koppelservice niet beschikbaar.',
  'Waiting for the other device': 'Wachten op het andere apparaat',
  'Motion access was not granted.': 'Toegang tot beweging is niet toegestaan.',
  'Pairing code copied.': 'Koppelcode gekopieerd.',
  'Pairing link copied.': 'Koppellink gekopieerd.',
  'Copy Code': 'Code kopiëren',
  'Copy Link': 'Link kopiëren',
  'Hide': 'Verbergen',
  'Pair by Code': 'Koppelen met code',
  'Pair': 'Koppelen',
  'Controller': 'Controller',
  'Table Display': 'Tafelweergave',
  'Disconnect Table Display': 'Tafelweergave loskoppelen',
  'Table Display shape interaction': 'Vorminteractie tafelweergave',
  'Table Display shapes visible': 'Vormen tafelweergave zichtbaar',
  'Turn off all ripples': 'Alle rimpels uitschakelen',
  'Table name': 'Tafelnaam',
  'OK': 'OK',
  'Restore previous autosave?': 'Vorige automatische opslag herstellen?',
  'Restore': 'Herstellen',
  'Previous autosave restored. Undo can reverse it.': 'Vorige automatische opslag hersteld. Ongedaan maken kan dit terugdraaien.',
  'Saved a copy.': 'Kopie opgeslagen.',
  'Table saved.': 'Tafel opgeslagen.',
  'No saved tables yet.': 'Nog geen opgeslagen tafels.',
  'Delete saved table': 'Opgeslagen tafel verwijderen',
  'Table JSON saved.': 'Tafel-JSON opgeslagen.',
  'That file is not a LightHouse table.': 'Dat bestand is geen LightHouse-tafel.',
  'Could not read that table file.': 'Kon dat tafelbestand niet lezen.',
  'Orientation lock': 'Oriëntatievergrendeling',
  'Display settings': 'Weergave-instellingen',
  'Table brightness': 'Tafelhelderheid',
  'Use system': 'Systeem gebruiken',
  'Different rule': 'Andere regel',
  'Hide rule': 'Regel verbergen',
  'Press/release to roll; two-finger drag moves; latch tiles cycle die counts': 'Indrukken/loslaten om te gooien; slepen met twee vingers verplaatst; vergrendeltegels wijzigen het aantal dobbelstenen',
  'Tap or hold/release to roll; two-finger drag moves; pinch resizes; latch tiles cycle die counts': 'Tik of houd vast/laat los om te gooien; slepen met twee vingers verplaatst; knijpen wijzigt de grootte; vergrendeltegels wijzigen het aantal dobbelstenen',
  'Tap or drag from tray; drag stones; double-click to remove': 'Tik of sleep vanuit de lade; sleep stenen; dubbelklik om te verwijderen',
  'Tap or drag from tray; drag stones; double-tap to remove': 'Tik of sleep vanuit de lade; sleep stenen; dubbeltik om te verwijderen',
  'Place a Large pyramid upright over the filled square. Adjust the slider until its base matches the square exactly.': 'Plaats een grote piramide rechtop op het gevulde vierkant. Pas de schuif aan tot de basis exact overeenkomt.',
  'Hold a ruler to the screen with 0 aligned to the fixed left end. Adjust the slider until the right end reaches exactly 50 mm.': 'Houd een liniaal tegen het scherm met 0 op het vaste linkereinde. Pas de schuif aan tot het rechtereinde exact 50 mm bereikt.',
  'LightHouse locks the table to one orientation while it is open. Android can open the system Display settings directly.': 'LightHouse vergrendelt de tafel in één oriëntatie zolang deze open is. Android kan de systeeminstellingen voor weergave rechtstreeks openen.',
  'LightHouse locks the table while it is open. iOS does not provide a supported app link to Rotation Lock; change it in Control Center.': 'LightHouse vergrendelt de tafel zolang deze open is. iOS biedt geen ondersteunde app-link naar rotatievergrendeling; wijzig dit in het Bedieningspaneel.',
  'Orientation locking depends on browser and platform support.': 'Oriëntatievergrendeling hangt af van browser- en platformondersteuning.',
  'Browsers cannot control screen brightness. Use the device brightness control.': 'Browsers kunnen de schermhelderheid niet regelen. Gebruik de helderheidsregeling van het apparaat.',
  'iOS does not expose a supported deep link to its Brightness panel; use Control Center for the system setting.': 'iOS biedt geen ondersteunde directe link naar Helderheid; gebruik het Bedieningspaneel.',
  'On iPhone or iPad, open this site in Safari, tap Share, then Add to Home Screen. On desktop browsers, use the browser install-app command when offered.': 'Open deze site op iPhone of iPad in Safari, tik op Delen en vervolgens op Zet op beginscherm. Gebruik op desktop de installatieoptie van de browser wanneer die wordt aangeboden.',
  '6-Character Code': 'Code van 6 tekens',
  'QR / Link': 'QR / link',
  'Could not open Android display settings.': 'Kon de Android-weergave-instellingen niet openen.',
};

const _pt = <String, String>{
  'Desktop / trackpad': 'Computador / trackpad',
  'Android tablet': 'Tablet Android',
  'Android phone': 'Telefone Android',
  'Touch device': 'Dispositivo tátil',
  'Light Lottery': 'Loteria de luz',
  'Entropy Delete': 'Exclusão entrópica',
  'Turn Timer': 'Temporizador de turno',
  'Red Sweep': 'Varredura vermelha',
  'Ghost Paths': 'Trilhas fantasmas',
  'Random Event Zone': 'Zona de evento aleatório',
  'Breathing': 'Respiração',
  'Nest Cycle': 'Ciclo de ninho',
  'Radar': 'Radar',
  'Dice Bubble': 'Bolha de dados',
  'Side Guns': 'Canhões laterais',
  'Corner Ricochet': 'Ricochete de canto',
  'Hot Potato': 'Batata quente',
  'Constellation Draw': 'Desenhar constelação',
  'Heartbeat': 'Batimento cardíaco',
  'Triangle Bounce': 'Salto triangular',
  'Square Chase': 'Perseguição quadrada',
  'Thanks for playing with LightHouse!': 'Obrigado por jogar com o LightHouse!',
  'Menu': 'Menu',
  'File': 'Arquivo',
  'Edit': 'Editar',
  'Boards': 'Tabuleiros',
  'Toys': 'Brinquedos',
  'Display': 'Tela',
  'Remote': 'Remoto',
  'Instructions': 'Instruções',
  'New': 'Novo',
  'Open…': 'Abrir…',
  'Restore Previous Autosave…': 'Restaurar salvamento automático anterior…',
  'Save': 'Salvar',
  'Save a Copy…': 'Salvar uma cópia…',
  'Rename…': 'Renomear…',
  'Import Table JSON…': 'Importar JSON da mesa…',
  'Export Table JSON…': 'Exportar JSON da mesa…',
  'Undo': 'Desfazer',
  'Redo': 'Refazer',
  'Rotation Snap': 'Encaixe de rotação',
  'Free Rotation': 'Rotação livre',
  'Snap Now': 'Encaixar agora',
  'Game Boards': 'Tabuleiros de jogo',
  'Grids': 'Grades',
  'Martian Chess': 'Xadrez marciano',
  'Snap pieces to board': 'Encaixar peças no tabuleiro',
  'None': 'Nenhum',
  'Checker Shading': 'Sombreamento xadrez',
  'Size': 'Tamanho',
  'Safety Points': 'Pontas seguras',
  'Brightness': 'Brilho',
  'Orientation Lock': 'Bloqueio de orientação',
  'Full-screen': 'Tela cheia',
  'Zendo Off · Normal LightHouse': 'Zendo desligado · LightHouse normal',
  'Zendo Stones': 'Pedras Zendo',
  'Classic': 'Clássico',
  'Classic + Zendo 2.0': 'Clássico + Zendo 2.0',
  'Zendo Rule': 'Regra Zendo',
  'Different Zendo Rule': 'Outra regra Zendo',
  'Complex Rules': 'Regras complexas',
  'Hide Active Rule': 'Ocultar regra ativa',
  'Show Active Rule': 'Mostrar regra ativa',
  'Easy': 'Fácil',
  'Medium': 'Médio',
  'Medium Hard': 'Médio difícil',
  'Hard': 'Difícil',
  'Crazy Hard': 'Muito difícil',
  'Difficulty': 'Dificuldade',
  'This Device: Table Display': 'Este dispositivo: Tela da mesa',
  'This Device: Controller': 'Este dispositivo: Controlador',
  'Pair with 6-Character Code': 'Parear com código de 6 caracteres',
  'Pair with QR / Link': 'Parear com QR / link',
  'Add Another Controller': 'Adicionar outro controlador',
  'Show Pairing QR': 'Mostrar QR de pareamento',
  'Swap Roles': 'Trocar funções',
  'Disconnect': 'Desconectar',
  'Turn Off All Ripples': 'Desligar todas as ondas',
  'Table Display Shape Interaction': 'Interação com formas na tela da mesa',
  'Table Display Shapes Visible': 'Formas visíveis na tela da mesa',
  'Create / resize / delete': 'Criar / redimensionar / excluir',
  'Double-click': 'Clique duplo',
  'Double-tap': 'Toque duplo',
  'Tip / stand': 'Deitar / levantar',
  'Drag through the footprint edge': 'Arrastar através da borda da base',
  'Full / wall light': 'Luz total / lateral',
  'Draw a loop around an upright footprint': 'Desenhar um laço ao redor de uma base vertical',
  'Move': 'Mover',
  'Two-finger scroll over a footprint': 'Rolar com dois dedos sobre uma base',
  'Rotate': 'Girar',
  'Shift + two-finger scroll': 'Shift + rolagem com dois dedos',
  'Move + rotate': 'Mover + girar',
  'Two-finger drag and twist': 'Arrastar e girar com dois dedos',
  'Rotation snap': 'Encaixe de rotação',
  'Edit > Rotation Snap; Snap Now aligns every shape immediately': 'Editar > Encaixe de rotação; Encaixar agora alinha todas as formas imediatamente',
  'Board snap': 'Encaixe no tabuleiro',
  'Boards > Snap pieces to board': 'Tabuleiros > Encaixar peças no tabuleiro',
  'Dice bubble': 'Bolha de dados',
  'Zendo stones': 'Pedras Zendo',
  'Remote ripple': 'Onda remota',
  'On a Controller, hold a shape to start its ripple; hold again to stop it': 'No controlador, segure uma forma para iniciar a onda; segure novamente para parar',
  'Toys chooses controls; hold an icon for its name': 'Brinquedos escolhe controles; segure um ícone para ver o nome',
  'Close instructions': 'Fechar instruções',
  'Calibrate physical size': 'Calibrar tamanho físico',
  'Ruler': 'Régua',
  'Large pyramid': 'Pirâmide grande',
  'Cancel': 'Cancelar',
  'Use calibration': 'Usar calibração',
  'A Large upright pyramid should fit this square:': 'Uma pirâmide grande em pé deve caber exatamente neste quadrado:',
  'Cross-check: this bar should measure exactly 25 mm:': 'Conferência: esta barra deve medir exatamente 25 mm:',
  'Recalibrate': 'Recalibrar',
  'Looks right': 'Parece certo',
  'Manual calibration': 'Calibração manual',
  'Dice': 'Dados',
  'selected': 'selecionado',
  'Regular D6': 'D6 normal',
  'Lightning die': 'Dado relâmpago',
  'Pyramid die': 'Dado pirâmide',
  'Treehouse die': 'Dado Treehouse',
  'Color die': 'Dado de cor',
  'Fudge / Fate die': 'Dado Fudge / Fate',
  'Remove one': 'Remover um',
  'Add one': 'Adicionar um',
  'Done': 'Concluído',
  'increments': 'incrementos',
  'Pairing code': 'Código de pareamento',
  'Type the same 6-character code on both devices.': 'Digite o mesmo código de 6 caracteres nos dois dispositivos.',
  'Enter exactly 6 letters or digits.': 'Digite exatamente 6 letras ou dígitos.',
  'Add Controller': 'Adicionar controlador',
  'Pair Controller': 'Parear controlador',
  'Pair Table Display': 'Parear tela da mesa',
  'Enter this same code on the other device and choose the opposite role.': 'Digite este mesmo código no outro dispositivo e escolha a função oposta.',
  'Paired': 'Pareado',
  'Pairing service unavailable.': 'Serviço de pareamento indisponível.',
  'Waiting for the other device': 'Aguardando o outro dispositivo',
  'Motion access was not granted.': 'O acesso ao movimento não foi concedido.',
  'Pairing code copied.': 'Código de pareamento copiado.',
  'Pairing link copied.': 'Link de pareamento copiado.',
  'Copy Code': 'Copiar código',
  'Copy Link': 'Copiar link',
  'Hide': 'Ocultar',
  'Pair by Code': 'Parear por código',
  'Pair': 'Parear',
  'Controller': 'Controlador',
  'Table Display': 'Tela da mesa',
  'Disconnect Table Display': 'Desconectar tela da mesa',
  'Table Display shape interaction': 'Interação das formas na tela da mesa',
  'Table Display shapes visible': 'Formas da tela da mesa visíveis',
  'Turn off all ripples': 'Desligar todas as ondas',
  'Table name': 'Nome da mesa',
  'OK': 'OK',
  'Restore previous autosave?': 'Restaurar salvamento automático anterior?',
  'Restore': 'Restaurar',
  'Previous autosave restored. Undo can reverse it.': 'Salvamento automático anterior restaurado. Desfazer pode reverter.',
  'Saved a copy.': 'Cópia salva.',
  'Table saved.': 'Mesa salva.',
  'No saved tables yet.': 'Ainda não há mesas salvas.',
  'Delete saved table': 'Excluir mesa salva',
  'Table JSON saved.': 'JSON da mesa salvo.',
  'That file is not a LightHouse table.': 'Esse arquivo não é uma mesa LightHouse.',
  'Could not read that table file.': 'Não foi possível ler esse arquivo de mesa.',
  'Orientation lock': 'Bloqueio de orientação',
  'Display settings': 'Configurações de tela',
  'Table brightness': 'Brilho da mesa',
  'Use system': 'Usar sistema',
  'Different rule': 'Outra regra',
  'Hide rule': 'Ocultar regra',
  'Press/release to roll; two-finger drag moves; latch tiles cycle die counts': 'Pressione/solte para rolar; arraste com dois dedos para mover; as peças de trava alteram a quantidade de dados',
  'Tap or hold/release to roll; two-finger drag moves; pinch resizes; latch tiles cycle die counts': 'Toque ou segure/solte para rolar; arraste com dois dedos para mover; faça pinça para redimensionar; as peças de trava alteram a quantidade de dados',
  'Tap or drag from tray; drag stones; double-click to remove': 'Toque ou arraste da bandeja; arraste as pedras; clique duplo para remover',
  'Tap or drag from tray; drag stones; double-tap to remove': 'Toque ou arraste da bandeja; arraste as pedras; toque duplo para remover',
  'Place a Large pyramid upright over the filled square. Adjust the slider until its base matches the square exactly.': 'Coloque uma pirâmide grande em pé sobre o quadrado preenchido. Ajuste o controle até que a base coincida exatamente.',
  'Hold a ruler to the screen with 0 aligned to the fixed left end. Adjust the slider until the right end reaches exactly 50 mm.': 'Segure uma régua na tela com o 0 alinhado à extremidade esquerda fixa. Ajuste o controle até a extremidade direita chegar exatamente a 50 mm.',
  'LightHouse locks the table to one orientation while it is open. Android can open the system Display settings directly.': 'O LightHouse fixa a mesa em uma orientação enquanto estiver aberto. O Android pode abrir diretamente as configurações de tela do sistema.',
  'LightHouse locks the table while it is open. iOS does not provide a supported app link to Rotation Lock; change it in Control Center.': 'O LightHouse fixa a mesa enquanto estiver aberto. O iOS não oferece link compatível para o bloqueio de rotação; altere no Centro de Controle.',
  'Orientation locking depends on browser and platform support.': 'O bloqueio de orientação depende do navegador e da plataforma.',
  'Browsers cannot control screen brightness. Use the device brightness control.': 'Navegadores não podem controlar o brilho da tela. Use o controle de brilho do dispositivo.',
  'iOS does not expose a supported deep link to its Brightness panel; use Control Center for the system setting.': 'O iOS não oferece link direto compatível para o painel de brilho; use o Centro de Controle.',
  'On iPhone or iPad, open this site in Safari, tap Share, then Add to Home Screen. On desktop browsers, use the browser install-app command when offered.': 'No iPhone ou iPad, abra este site no Safari, toque em Compartilhar e depois em Adicionar à Tela de Início. No computador, use o comando de instalar aplicativo quando oferecido.',
  '6-Character Code': 'Código de 6 caracteres',
  'QR / Link': 'QR / link',
  'Could not open Android display settings.': 'Não foi possível abrir as configurações de tela do Android.',
};

const _zh = <String, String>{
  'Desktop / trackpad': '桌面 / 触控板',
  'Android tablet': 'Android 平板',
  'Android phone': 'Android 手机',
  'Touch device': '触控设备',
  'Light Lottery': '光线抽奖',
  'Entropy Delete': '熵删除',
  'Turn Timer': '回合计时器',
  'Red Sweep': '红色扫描',
  'Ghost Paths': '幽灵轨迹',
  'Random Event Zone': '随机事件区域',
  'Breathing': '呼吸',
  'Nest Cycle': '嵌套循环',
  'Radar': '雷达',
  'Dice Bubble': '骰子泡泡',
  'Side Guns': '侧边炮',
  'Corner Ricochet': '角落反弹',
  'Hot Potato': '烫手山芋',
  'Constellation Draw': '星座连线',
  'Heartbeat': '心跳',
  'Triangle Bounce': '三角弹跳',
  'Square Chase': '方形追逐',
  'Thanks for playing with LightHouse!': '感谢使用 LightHouse 玩耍！',
  'Menu': '菜单',
  'File': '文件',
  'Edit': '编辑',
  'Boards': '棋盘',
  'Toys': '玩具',
  'Display': '显示',
  'Remote': '远程',
  'Instructions': '说明',
  'New': '新建',
  'Open…': '打开…',
  'Restore Previous Autosave…': '恢复上一次自动保存…',
  'Save': '保存',
  'Save a Copy…': '保存副本…',
  'Rename…': '重命名…',
  'Import Table JSON…': '导入桌面 JSON…',
  'Export Table JSON…': '导出桌面 JSON…',
  'Undo': '撤销',
  'Redo': '重做',
  'Rotation Snap': '旋转吸附',
  'Free Rotation': '自由旋转',
  'Snap Now': '立即吸附',
  'Game Boards': '游戏棋盘',
  'Grids': '网格',
  'Martian Chess': '火星棋',
  'Snap pieces to board': '将棋子吸附到棋盘',
  'None': '无',
  'Checker Shading': '棋盘格阴影',
  'Size': '尺寸',
  'Safety Points': '安全尖角',
  'Brightness': '亮度',
  'Orientation Lock': '方向锁定',
  'Full-screen': '全屏',
  'Zendo Off · Normal LightHouse': '关闭 Zendo · 普通 LightHouse',
  'Zendo Stones': 'Zendo 石',
  'Classic': '经典',
  'Classic + Zendo 2.0': '经典 + Zendo 2.0',
  'Zendo Rule': 'Zendo 规则',
  'Different Zendo Rule': '更换 Zendo 规则',
  'Complex Rules': '复杂规则',
  'Hide Active Rule': '隐藏当前规则',
  'Show Active Rule': '显示当前规则',
  'Easy': '简单',
  'Medium': '中等',
  'Medium Hard': '中等偏难',
  'Hard': '困难',
  'Crazy Hard': '非常困难',
  'Difficulty': '难度',
  'This Device: Table Display': '此设备：桌面显示器',
  'This Device: Controller': '此设备：控制器',
  'Pair with 6-Character Code': '使用 6 位代码配对',
  'Pair with QR / Link': '使用二维码 / 链接配对',
  'Add Another Controller': '添加另一个控制器',
  'Show Pairing QR': '显示配对二维码',
  'Swap Roles': '交换角色',
  'Disconnect': '断开连接',
  'Turn Off All Ripples': '关闭所有波纹',
  'Table Display Shape Interaction': '桌面显示器形状交互',
  'Table Display Shapes Visible': '桌面显示器形状可见',
  'Create / resize / delete': '创建 / 调整大小 / 删除',
  'Double-click': '双击',
  'Double-tap': '双击触摸',
  'Tip / stand': '放倒 / 立起',
  'Drag through the footprint edge': '拖过底面边缘',
  'Full / wall light': '全亮 / 侧壁亮',
  'Draw a loop around an upright footprint': '围绕直立底面画一圈',
  'Move': '移动',
  'Two-finger scroll over a footprint': '在底面上双指滚动',
  'Rotate': '旋转',
  'Shift + two-finger scroll': 'Shift + 双指滚动',
  'Move + rotate': '移动 + 旋转',
  'Two-finger drag and twist': '双指拖动并旋转',
  'Rotation snap': '旋转吸附',
  'Edit > Rotation Snap; Snap Now aligns every shape immediately': '编辑 > 旋转吸附；“立即吸附”会立刻对齐所有形状',
  'Board snap': '棋盘吸附',
  'Boards > Snap pieces to board': '棋盘 > 将棋子吸附到棋盘',
  'Dice bubble': '骰子泡泡',
  'Zendo stones': 'Zendo 石',
  'Remote ripple': '远程波纹',
  'On a Controller, hold a shape to start its ripple; hold again to stop it': '在控制器上长按形状开始波纹；再次长按停止',
  'Toys chooses controls; hold an icon for its name': '“玩具”用于选择控件；长按图标查看名称',
  'Close instructions': '关闭说明',
  'Calibrate physical size': '校准实际尺寸',
  'Ruler': '尺子',
  'Large pyramid': '大号金字塔',
  'Cancel': '取消',
  'Use calibration': '使用校准',
  'A Large upright pyramid should fit this square:': '一枚直立的大号金字塔应正好放入此方框：',
  'Cross-check: this bar should measure exactly 25 mm:': '复核：此条应正好为 25 mm：',
  'Recalibrate': '重新校准',
  'Looks right': '看起来正确',
  'Manual calibration': '手动校准',
  'Dice': '骰子',
  'selected': '已选择',
  'Regular D6': '普通 D6',
  'Lightning die': '闪电骰',
  'Pyramid die': '金字塔骰',
  'Treehouse die': 'Treehouse 骰',
  'Color die': '颜色骰',
  'Fudge / Fate die': 'Fudge / Fate 骰',
  'Remove one': '减少一个',
  'Add one': '增加一个',
  'Done': '完成',
  'increments': '增量',
  'Pairing code': '配对代码',
  'Type the same 6-character code on both devices.': '在两台设备上输入相同的 6 位代码。',
  'Enter exactly 6 letters or digits.': '请输入恰好 6 个字母或数字。',
  'Add Controller': '添加控制器',
  'Pair Controller': '配对控制器',
  'Pair Table Display': '配对桌面显示器',
  'Enter this same code on the other device and choose the opposite role.': '在另一台设备上输入相同代码并选择相反角色。',
  'Paired': '已配对',
  'Pairing service unavailable.': '配对服务不可用。',
  'Waiting for the other device': '正在等待另一台设备',
  'Motion access was not granted.': '未授予运动传感器权限。',
  'Pairing code copied.': '已复制配对代码。',
  'Pairing link copied.': '已复制配对链接。',
  'Copy Code': '复制代码',
  'Copy Link': '复制链接',
  'Hide': '隐藏',
  'Pair by Code': '通过代码配对',
  'Pair': '配对',
  'Controller': '控制器',
  'Table Display': '桌面显示器',
  'Disconnect Table Display': '断开桌面显示器',
  'Table Display shape interaction': '桌面显示器形状交互',
  'Table Display shapes visible': '桌面显示器形状可见',
  'Turn off all ripples': '关闭所有波纹',
  'Table name': '桌面名称',
  'OK': '确定',
  'Restore previous autosave?': '恢复上一次自动保存？',
  'Restore': '恢复',
  'Previous autosave restored. Undo can reverse it.': '已恢复上一次自动保存，可用“撤销”恢复。',
  'Saved a copy.': '副本已保存。',
  'Table saved.': '桌面已保存。',
  'No saved tables yet.': '尚无已保存桌面。',
  'Delete saved table': '删除已保存桌面',
  'Table JSON saved.': '桌面 JSON 已保存。',
  'That file is not a LightHouse table.': '该文件不是 LightHouse 桌面文件。',
  'Could not read that table file.': '无法读取该桌面文件。',
  'Orientation lock': '方向锁定',
  'Display settings': '显示设置',
  'Table brightness': '桌面亮度',
  'Use system': '使用系统设置',
  'Different rule': '更换规则',
  'Hide rule': '隐藏规则',
  'Press/release to roll; two-finger drag moves; latch tiles cycle die counts': '按下/松开掷骰；双指拖动可移动；锁扣方块可切换骰子数量',
  'Tap or hold/release to roll; two-finger drag moves; pinch resizes; latch tiles cycle die counts': '点击或长按/松开掷骰；双指拖动可移动；双指捏合可调整大小；锁扣方块可切换骰子数量',
  'Tap or drag from tray; drag stones; double-click to remove': '从托盘点击或拖出；拖动石块；双击删除',
  'Tap or drag from tray; drag stones; double-tap to remove': '从托盘点击或拖出；拖动石块；双击触摸删除',
  'Place a Large pyramid upright over the filled square. Adjust the slider until its base matches the square exactly.': '将大号金字塔直立放在实心方框上，调节滑块直到底面与方框完全吻合。',
  'Hold a ruler to the screen with 0 aligned to the fixed left end. Adjust the slider until the right end reaches exactly 50 mm.': '将尺子的 0 对准固定左端，调节滑块直到右端恰好到达 50 mm。',
  'LightHouse locks the table to one orientation while it is open. Android can open the system Display settings directly.': 'LightHouse 打开时会将桌面锁定为一个方向。Android 可直接打开系统显示设置。',
  'LightHouse locks the table while it is open. iOS does not provide a supported app link to Rotation Lock; change it in Control Center.': 'LightHouse 打开时会锁定桌面。iOS 不提供可用的旋转锁定链接，请在控制中心修改。',
  'Orientation locking depends on browser and platform support.': '方向锁定取决于浏览器和平台支持。',
  'Browsers cannot control screen brightness. Use the device brightness control.': '浏览器无法控制屏幕亮度，请使用设备的亮度控制。',
  'iOS does not expose a supported deep link to its Brightness panel; use Control Center for the system setting.': 'iOS 不提供亮度面板的可用直接链接；请使用控制中心。',
  'On iPhone or iPad, open this site in Safari, tap Share, then Add to Home Screen. On desktop browsers, use the browser install-app command when offered.': '在 iPhone 或 iPad 上用 Safari 打开本网站，点“共享”，再点“添加到主屏幕”。在桌面浏览器中，当出现安装应用选项时使用它。',
  '6-Character Code': '6 位代码',
  'QR / Link': '二维码 / 链接',
  'Could not open Android display settings.': '无法打开 Android 显示设置。',
};

const _it = <String, String>{
  'Desktop / trackpad': 'Desktop / trackpad',
  'Android tablet': 'Tablet Android',
  'Android phone': 'Telefono Android',
  'Touch device': 'Dispositivo touch',
  'Light Lottery': 'Lotteria della luce',
  'Entropy Delete': 'Eliminazione entropica',
  'Turn Timer': 'Timer del turno',
  'Red Sweep': 'Scansione rossa',
  'Ghost Paths': 'Percorsi fantasma',
  'Random Event Zone': 'Zona evento casuale',
  'Breathing': 'Respirazione',
  'Nest Cycle': 'Ciclo nido',
  'Radar': 'Radar',
  'Dice Bubble': 'Bolla dei dadi',
  'Side Guns': 'Cannoni laterali',
  'Corner Ricochet': 'Rimbalzo d\'angolo',
  'Hot Potato': 'Patata bollente',
  'Constellation Draw': 'Disegna costellazione',
  'Heartbeat': 'Battito cardiaco',
  'Triangle Bounce': 'Rimbalzo triangolare',
  'Square Chase': 'Inseguimento quadrato',
  'Thanks for playing with LightHouse!': 'Grazie per aver giocato con LightHouse!',
  'Menu': 'Menu',
  'File': 'File',
  'Edit': 'Modifica',
  'Boards': 'Tabelloni',
  'Toys': 'Giochi',
  'Display': 'Schermo',
  'Remote': 'Remoto',
  'Instructions': 'Istruzioni',
  'New': 'Nuovo',
  'Open…': 'Apri…',
  'Restore Previous Autosave…': 'Ripristina salvataggio automatico precedente…',
  'Save': 'Salva',
  'Save a Copy…': 'Salva una copia…',
  'Rename…': 'Rinomina…',
  'Import Table JSON…': 'Importa JSON del tavolo…',
  'Export Table JSON…': 'Esporta JSON del tavolo…',
  'Undo': 'Annulla',
  'Redo': 'Ripeti',
  'Rotation Snap': 'Scatto di rotazione',
  'Free Rotation': 'Rotazione libera',
  'Snap Now': 'Allinea ora',
  'Game Boards': 'Tabelloni di gioco',
  'Grids': 'Griglie',
  'Martian Chess': 'Scacchi marziani',
  'Snap pieces to board': 'Allinea i pezzi al tabellone',
  'None': 'Nessuno',
  'Checker Shading': 'Ombreggiatura a scacchiera',
  'Size': 'Dimensione',
  'Safety Points': 'Punte sicure',
  'Brightness': 'Luminosità',
  'Orientation Lock': 'Blocco orientamento',
  'Full-screen': 'Schermo intero',
  'Zendo Off · Normal LightHouse': 'Zendo disattivato · LightHouse normale',
  'Zendo Stones': 'Pietre Zendo',
  'Classic': 'Classico',
  'Classic + Zendo 2.0': 'Classico + Zendo 2.0',
  'Zendo Rule': 'Regola Zendo',
  'Different Zendo Rule': 'Altra regola Zendo',
  'Complex Rules': 'Regole complesse',
  'Hide Active Rule': 'Nascondi regola attiva',
  'Show Active Rule': 'Mostra regola attiva',
  'Easy': 'Facile',
  'Medium': 'Medio',
  'Medium Hard': 'Medio-difficile',
  'Hard': 'Difficile',
  'Crazy Hard': 'Molto difficile',
  'Difficulty': 'Difficoltà',
  'This Device: Table Display': 'Questo dispositivo: Schermo tavolo',
  'This Device: Controller': 'Questo dispositivo: Controller',
  'Pair with 6-Character Code': 'Abbina con codice di 6 caratteri',
  'Pair with QR / Link': 'Abbina con QR / link',
  'Add Another Controller': 'Aggiungi un altro controller',
  'Show Pairing QR': 'Mostra QR di abbinamento',
  'Swap Roles': 'Scambia ruoli',
  'Disconnect': 'Disconnetti',
  'Turn Off All Ripples': 'Disattiva tutte le onde',
  'Table Display Shape Interaction': 'Interazione con le forme sullo schermo tavolo',
  'Table Display Shapes Visible': 'Forme visibili sullo schermo tavolo',
  'Create / resize / delete': 'Crea / ridimensiona / elimina',
  'Double-click': 'Doppio clic',
  'Double-tap': 'Doppio tocco',
  'Tip / stand': 'Inclina / raddrizza',
  'Drag through the footprint edge': 'Trascina oltre il bordo dell\'impronta',
  'Full / wall light': 'Luce piena / laterale',
  'Draw a loop around an upright footprint': 'Disegna un anello attorno a un\'impronta verticale',
  'Move': 'Sposta',
  'Two-finger scroll over a footprint': 'Scorri con due dita su un\'impronta',
  'Rotate': 'Ruota',
  'Shift + two-finger scroll': 'Maiusc + scorrimento con due dita',
  'Move + rotate': 'Sposta + ruota',
  'Two-finger drag and twist': 'Trascina e ruota con due dita',
  'Rotation snap': 'Scatto di rotazione',
  'Edit > Rotation Snap; Snap Now aligns every shape immediately': 'Modifica > Scatto di rotazione; Allinea ora allinea immediatamente tutte le forme',
  'Board snap': 'Scatto al tabellone',
  'Boards > Snap pieces to board': 'Tabelloni > Allinea i pezzi al tabellone',
  'Dice bubble': 'Bolla dei dadi',
  'Zendo stones': 'Pietre Zendo',
  'Remote ripple': 'Onda remota',
  'On a Controller, hold a shape to start its ripple; hold again to stop it': 'Su un controller, tieni premuta una forma per avviare la sua onda; tieni premuto di nuovo per fermarla',
  'Toys chooses controls; hold an icon for its name': 'Giochi seleziona i controlli; tieni premuta un\'icona per vederne il nome',
  'Close instructions': 'Chiudi istruzioni',
  'Calibrate physical size': 'Calibra dimensione fisica',
  'Ruler': 'Righello',
  'Large pyramid': 'Piramide grande',
  'Cancel': 'Annulla',
  'Use calibration': 'Usa calibrazione',
  'A Large upright pyramid should fit this square:': 'Una piramide grande in verticale dovrebbe entrare esattamente in questo quadrato:',
  'Cross-check: this bar should measure exactly 25 mm:': 'Controllo: questa barra dovrebbe misurare esattamente 25 mm:',
  'Recalibrate': 'Ricalibra',
  'Looks right': 'Sembra corretto',
  'Manual calibration': 'Calibrazione manuale',
  'Dice': 'Dadi',
  'selected': 'selezionato',
  'Regular D6': 'D6 normale',
  'Lightning die': 'Dado fulmine',
  'Pyramid die': 'Dado piramide',
  'Treehouse die': 'Dado Treehouse',
  'Color die': 'Dado colore',
  'Fudge / Fate die': 'Dado Fudge / Fate',
  'Remove one': 'Rimuovine uno',
  'Add one': 'Aggiungine uno',
  'Done': 'Fatto',
  'increments': 'incrementi',
  'Pairing code': 'Codice di abbinamento',
  'Type the same 6-character code on both devices.': 'Inserisci lo stesso codice di 6 caratteri su entrambi i dispositivi.',
  'Enter exactly 6 letters or digits.': 'Inserisci esattamente 6 lettere o cifre.',
  'Add Controller': 'Aggiungi controller',
  'Pair Controller': 'Abbina controller',
  'Pair Table Display': 'Abbina schermo tavolo',
  'Enter this same code on the other device and choose the opposite role.': 'Inserisci lo stesso codice sull\'altro dispositivo e scegli il ruolo opposto.',
  'Paired': 'Abbinato',
  'Pairing service unavailable.': 'Servizio di abbinamento non disponibile.',
  'Waiting for the other device': 'In attesa dell\'altro dispositivo',
  'Motion access was not granted.': 'L\'accesso ai sensori di movimento non è stato concesso.',
  'Pairing code copied.': 'Codice di abbinamento copiato.',
  'Pairing link copied.': 'Link di abbinamento copiato.',
  'Copy Code': 'Copia codice',
  'Copy Link': 'Copia link',
  'Hide': 'Nascondi',
  'Pair by Code': 'Abbina con codice',
  'Pair': 'Abbina',
  'Controller': 'Controller',
  'Table Display': 'Schermo tavolo',
  'Disconnect Table Display': 'Disconnetti schermo tavolo',
  'Table Display shape interaction': 'Interazione forme dello schermo tavolo',
  'Table Display shapes visible': 'Forme dello schermo tavolo visibili',
  'Turn off all ripples': 'Disattiva tutte le onde',
  'Table name': 'Nome del tavolo',
  'OK': 'OK',
  'Restore previous autosave?': 'Ripristinare il salvataggio automatico precedente?',
  'Restore': 'Ripristina',
  'Previous autosave restored. Undo can reverse it.': 'Salvataggio automatico precedente ripristinato. Annulla può ripristinare lo stato precedente.',
  'Saved a copy.': 'Copia salvata.',
  'Table saved.': 'Tavolo salvato.',
  'No saved tables yet.': 'Nessun tavolo salvato.',
  'Delete saved table': 'Elimina tavolo salvato',
  'Table JSON saved.': 'JSON del tavolo salvato.',
  'That file is not a LightHouse table.': 'Quel file non è un tavolo LightHouse.',
  'Could not read that table file.': 'Impossibile leggere quel file del tavolo.',
  'Orientation lock': 'Blocco orientamento',
  'Display settings': 'Impostazioni schermo',
  'Table brightness': 'Luminosità del tavolo',
  'Use system': 'Usa sistema',
  'Different rule': 'Altra regola',
  'Hide rule': 'Nascondi regola',
  'Press/release to roll; two-finger drag moves; latch tiles cycle die counts': 'Premi/rilascia per lanciare; trascina con due dita per spostare; le tessere di blocco cambiano il numero di dadi',
  'Tap or hold/release to roll; two-finger drag moves; pinch resizes; latch tiles cycle die counts': 'Tocca o tieni premuto/rilascia per lanciare; trascina con due dita per spostare; pizzica per ridimensionare; le tessere di blocco cambiano il numero di dadi',
  'Tap or drag from tray; drag stones; double-click to remove': 'Tocca o trascina dal vassoio; trascina le pietre; doppio clic per rimuovere',
  'Tap or drag from tray; drag stones; double-tap to remove': 'Tocca o trascina dal vassoio; trascina le pietre; doppio tocco per rimuovere',
  'Place a Large pyramid upright over the filled square. Adjust the slider until its base matches the square exactly.': 'Posiziona una piramide grande in verticale sul quadrato pieno. Regola il cursore finché la base coincide esattamente con il quadrato.',
  'Hold a ruler to the screen with 0 aligned to the fixed left end. Adjust the slider until the right end reaches exactly 50 mm.': 'Tieni un righello sullo schermo con lo 0 allineato all\'estremità sinistra fissa. Regola il cursore finché l\'estremità destra raggiunge esattamente 50 mm.',
  'LightHouse locks the table to one orientation while it is open. Android can open the system Display settings directly.': 'LightHouse blocca il tavolo in un orientamento mentre è aperto. Android può aprire direttamente le impostazioni di schermo del sistema.',
  'LightHouse locks the table while it is open. iOS does not provide a supported app link to Rotation Lock; change it in Control Center.': 'LightHouse blocca il tavolo mentre è aperto. iOS non fornisce un link supportato al blocco rotazione; modificalo nel Centro di Controllo.',
  'Orientation locking depends on browser and platform support.': 'Il blocco dell\'orientamento dipende dal supporto del browser e della piattaforma.',
  'Browsers cannot control screen brightness. Use the device brightness control.': 'I browser non possono controllare la luminosità dello schermo. Usa il controllo della luminosità del dispositivo.',
  'iOS does not expose a supported deep link to its Brightness panel; use Control Center for the system setting.': 'iOS non espone un link diretto supportato al pannello Luminosità; usa il Centro di Controllo.',
  'On iPhone or iPad, open this site in Safari, tap Share, then Add to Home Screen. On desktop browsers, use the browser install-app command when offered.': 'Su iPhone o iPad, apri questo sito in Safari, tocca Condividi, quindi Aggiungi alla schermata Home. Sui browser desktop, usa il comando per installare l\'app quando viene proposto.',
  '6-Character Code': 'Codice di 6 caratteri',
  'QR / Link': 'QR / Link',
  'Could not open Android display settings.': 'Impossibile aprire le impostazioni schermo di Android.',
};

const _tok = <String, String>{
  'Desktop / trackpad': 'ilo supa / supa luka',
  'Android tablet': 'ilo supa Android',
  'Android phone': 'ilo toki Android',
  'Touch device': 'ilo pi luka',
  'Light Lottery': 'musi pi suno anu',
  'Entropy Delete': 'weka pi nasa',
  'Turn Timer': 'ilo tenpo pi tawa musi',
  'Red Sweep': 'tawa pi kule loje',
  'Ghost Paths': 'nasin kon',
  'Random Event Zone': 'ma pi ijo kama nasa',
  'Breathing': 'kon insa en kon weka',
  'Nest Cycle': 'sike poki',
  'Radar': 'ilo lukin weka',
  'Dice Bubble': 'sike ilo nanpa',
  'Side Guns': 'ilo utala poka',
  'Corner Ricochet': 'tawa sin tan poka',
  'Hot Potato': 'ijo seli',
  'Constellation Draw': 'sitelen kulupu mun',
  'Heartbeat': 'tawa pilin',
  'Triangle Bounce': 'tawa sin pi selo tu wan',
  'Square Chase': 'alasa pi selo tu tu',
  'Thanks for playing with LightHouse!': 'pona tawa sina tan musi lon LightHouse!',
  'Menu': 'lipu nasin',
  'File': 'lipu',
  'Edit': 'ante',
  'Boards': 'supa musi',
  'Toys': 'ilo musi',
  'Display': 'ilo lukin',
  'Remote': 'lawa weka',
  'Instructions': 'nasin kepeken',
  'New': 'sin',
  'Open…': 'o kama jo…',
  'Restore Previous Autosave…': 'o pana sin e awen pini…',
  'Save': 'o awen',
  'Save a Copy…': 'o awen e sama…',
  'Rename…': 'o ante e nimi…',
  'Import Table JSON…': 'o kama jo e lipu JSON pi supa…',
  'Export Table JSON…': 'o pana e lipu JSON pi supa…',
  'Undo': 'o weka e ante',
  'Redo': 'o pali sin e ante',
  'Rotation Snap': 'nasin sike',
  'Free Rotation': 'sike wile',
  'Snap Now': 'o pana lon nasin',
  'Game Boards': 'supa musi',
  'Grids': 'nasin kipisi',
  'Martian Chess': 'musi Martian Chess',
  'Snap pieces to board': 'o pana e ijo lon nasin supa',
  'None': 'ala',
  'Checker Shading': 'kule pi nasin tu',
  'Size': 'suli',
  'Safety Points': 'pini sewi pona',
  'Brightness': 'wawa suno',
  'Orientation Lock': 'awen nasin',
  'Full-screen': 'ilo lukin ale',
  'Zendo Off · Normal LightHouse': 'Zendo ala · LightHouse nasin',
  'Zendo Stones': 'kiwen Zendo',
  'Classic': 'nasin majuna',
  'Classic + Zendo 2.0': 'nasin majuna + Zendo 2.0',
  'Zendo Rule': 'lawa Zendo',
  'Different Zendo Rule': 'lawa Zendo ante',
  'Complex Rules': 'lawa mute',
  'Hide Active Rule': 'o len e lawa ni',
  'Show Active Rule': 'o lukin e lawa ni',
  'Easy': 'pona',
  'Medium': 'ike lili',
  'Medium Hard': 'ike',
  'Hard': 'ike mute',
  'Crazy Hard': 'ike suli a',
  'Difficulty': 'wawa ike',
  'This Device: Table Display': 'ilo ni: ilo lukin supa',
  'This Device: Controller': 'ilo ni: ilo lawa',
  'Pair with 6-Character Code': 'o wan kepeken sitelen 6',
  'Pair with QR / Link': 'o wan kepeken QR / nasin',
  'Add Another Controller': 'o pana e ilo lawa ante',
  'Show Pairing QR': 'o lukin e QR pi wan',
  'Swap Roles': 'o ante e pali',
  'Disconnect': 'o kipisi',
  'Turn Off All Ripples': 'o weka e sike ale',
  'Table Display Shape Interaction': 'pali ijo lon ilo lukin supa',
  'Table Display Shapes Visible': 'ijo li lukin lon ilo lukin supa',
  'Create / resize / delete': 'pali / ante suli / weka',
  'Double-click': 'o luka tu',
  'Double-tap': 'o luka tu',
  'Tip / stand': 'o anpa / o sewi',
  'Drag through the footprint edge': 'o tawa luka tawa poka pi ma ijo',
  'Full / wall light': 'suno ale / suno poka',
  'Draw a loop around an upright footprint': 'o sitelen e sike lon poka pi ma ijo sewi',
  'Move': 'tawa',
  'Two-finger scroll over a footprint': 'o tawa kepeken luka tu lon ma ijo',
  'Rotate': 'sike',
  'Shift + two-finger scroll': 'Shift + tawa luka tu',
  'Move + rotate': 'tawa + sike',
  'Two-finger drag and twist': 'o tawa o sike kepeken luka tu',
  'Rotation snap': 'nasin sike',
  'Edit > Rotation Snap; Snap Now aligns every shape immediately': 'Ante > nasin sike; o pana lon nasin li pona e nasin pi ijo ale lon tenpo ni',
  'Board snap': 'nasin supa',
  'Boards > Snap pieces to board': 'Supa musi > o pana e ijo lon nasin supa',
  'Dice bubble': 'sike ilo nanpa',
  'Zendo stones': 'kiwen Zendo',
  'Remote ripple': 'sike pi lawa weka',
  'On a Controller, hold a shape to start its ripple; hold again to stop it': 'lon ilo lawa, o awen e luka lon ijo la sike ona li open; o awen sin la sike li pini',
  'Toys chooses controls; hold an icon for its name': 'Ilo musi li lawa e ilo; o awen e luka lon sitelen la nimi ona li kama lukin',
  'Close instructions': 'o pini e nasin kepeken',
  'Calibrate physical size': 'o pona e suli lon',
  'Ruler': 'ilo pi sona suli',
  'Large pyramid': 'ijo sewi suli',
  'Cancel': 'o pini',
  'Use calibration': 'o kepeken e pona suli',
  'A Large upright pyramid should fit this square:': 'ijo sewi suli li sewi la ona o sama suli e selo tu tu ni:',
  'Cross-check: this bar should measure exactly 25 mm:': 'o sona sin: palisa ni o suli 25 mm taso:',
  'Recalibrate': 'o pona sin e suli',
  'Looks right': 'ni li pona',
  'Manual calibration': 'pona suli pi luka',
  'Dice': 'ilo nanpa',
  'selected': 'jo',
  'Regular D6': 'ilo nanpa D6',
  'Lightning die': 'ilo nanpa pi suno wawa',
  'Pyramid die': 'ilo nanpa pi ijo sewi',
  'Treehouse die': 'ilo nanpa Treehouse',
  'Color die': 'ilo nanpa pi kule',
  'Fudge / Fate die': 'ilo nanpa Fudge / Fate',
  'Remove one': 'o weka e wan',
  'Add one': 'o pana e wan',
  'Done': 'pini',
  'increments': 'ante lili',
  'Pairing code': 'sitelen pi wan',
  'Type the same 6-character code on both devices.': 'o sitelen e sitelen sama 6 lon ilo tu.',
  'Enter exactly 6 letters or digits.': 'o pana e sitelen anu nanpa 6 taso.',
  'Add Controller': 'o pana e ilo lawa',
  'Pair Controller': 'o wan e ilo lawa',
  'Pair Table Display': 'o wan e ilo lukin supa',
  'Enter this same code on the other device and choose the opposite role.': 'o pana e sitelen sama ni lon ilo ante, o wile e pali ante.',
  'Paired': 'ilo li wan',
  'Pairing service unavailable.': 'nasin pi wan ilo li ken ala.',
  'Waiting for the other device': 'mi awen e ilo ante',
  'Motion access was not granted.': 'ilo li ken ala sona e tawa.',
  'Pairing code copied.': 'sitelen pi wan li kama sama.',
  'Pairing link copied.': 'nasin pi wan li kama sama.',
  'Copy Code': 'o sama e sitelen',
  'Copy Link': 'o sama e nasin',
  'Hide': 'o len',
  'Pair by Code': 'o wan kepeken sitelen',
  'Pair': 'o wan',
  'Controller': 'ilo lawa',
  'Table Display': 'ilo lukin supa',
  'Disconnect Table Display': 'o kipisi e ilo lukin supa',
  'Table Display shape interaction': 'pali ijo pi ilo lukin supa',
  'Table Display shapes visible': 'ijo lukin pi ilo lukin supa',
  'Turn off all ripples': 'o weka e sike ale',
  'Table name': 'nimi supa',
  'OK': 'pona',
  'Restore previous autosave?': 'o pana sin e awen pini?',
  'Restore': 'o pana sin',
  'Previous autosave restored. Undo can reverse it.': 'awen pini li kama sin. o weka e ante li ken weka e ni.',
  'Saved a copy.': 'sama li awen.',
  'Table saved.': 'supa li awen.',
  'No saved tables yet.': 'supa awen li lon ala.',
  'Delete saved table': 'o weka e supa awen',
  'Table JSON saved.': 'lipu JSON pi supa li awen.',
  'That file is not a LightHouse table.': 'lipu ni li supa LightHouse ala.',
  'Could not read that table file.': 'mi ken ala lukin e lipu supa ni.',
  'Orientation lock': 'awen nasin',
  'Display settings': 'nasin ilo lukin',
  'Table brightness': 'wawa suno pi supa',
  'Use system': 'o kepeken e nasin ilo',
  'Different rule': 'lawa ante',
  'Hide rule': 'o len e lawa',
  'Press/release to roll; two-finger drag moves; latch tiles cycle die counts': 'o pilin o weka la ilo nanpa li tawa; luka tu li tawa e sike; lipu awen li ante e mute ilo nanpa',
  'Tap or hold/release to roll; two-finger drag moves; pinch resizes; latch tiles cycle die counts': 'o luka anu o awen o weka la ilo nanpa li tawa; luka tu li tawa e sike; luka tu li ante e suli; lipu awen li ante e mute ilo nanpa',
  'Tap or drag from tray; drag stones; double-click to remove': 'o luka anu o tawa tan poki; o tawa e kiwen; o luka tu la o weka',
  'Tap or drag from tray; drag stones; double-tap to remove': 'o luka anu o tawa tan poki; o tawa e kiwen; o luka tu la o weka',
  'Place a Large pyramid upright over the filled square. Adjust the slider until its base matches the square exactly.': 'o pana e ijo sewi suli lon sewi pi selo tu tu kule. o ante e ilo tawa tawa ni: anpa ona li sama suli e selo tu tu.',
  'Hold a ruler to the screen with 0 aligned to the fixed left end. Adjust the slider until the right end reaches exactly 50 mm.': 'o pana e ilo pi sona suli lon ilo lukin; 0 o lon pini open. o ante e ilo tawa tawa pini ante li lon 50 mm.',
  'LightHouse locks the table to one orientation while it is open. Android can open the system Display settings directly.': 'LightHouse li awen e nasin wan pi supa lon tenpo open. Android li ken open e nasin ilo lukin pi ilo.',
  'LightHouse locks the table while it is open. iOS does not provide a supported app link to Rotation Lock; change it in Control Center.': 'LightHouse li awen e supa lon tenpo open. iOS li ken ala open e nasin Rotation Lock; o ante e ona lon Control Center.',
  'Orientation locking depends on browser and platform support.': 'awen nasin li ken anu ken ala tan ilo lukin en nasin ilo.',
  'Browsers cannot control screen brightness. Use the device brightness control.': 'ilo lukin pi Internet li ken ala lawa e wawa suno. o kepeken e lawa suno pi ilo.',
  'iOS does not expose a supported deep link to its Brightness panel; use Control Center for the system setting.': 'iOS li pana ala e nasin tawa Brightness; o kepeken Control Center.',
  'On iPhone or iPad, open this site in Safari, tap Share, then Add to Home Screen. On desktop browsers, use the browser install-app command when offered.': 'lon iPhone anu iPad, o open e ma ni lon Safari, o luka e Share, o luka e Add to Home Screen. lon ilo supa, o kepeken e nasin pi pana ilo tan ilo lukin.',
  '6-Character Code': 'sitelen 6',
  'QR / Link': 'QR / nasin',
  'Could not open Android display settings.': 'mi ken ala open e nasin ilo lukin pi Android.',
};
